---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage-system
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: "10.32.1.5"
      path: "/mnt/lab-pool/k3s-nfs"
    storageClass:
      name: nfs-kube
      defaultClass: false