apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: dbms
stringData:
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Y2aGSI7X0I6kGVyOUvjs9rn0+EUHC+avaVRYxbnN,iv:ohbva6CPRhNKX/VDwLGEbwBzJ9HuRBw9Xr7IWig3XSs=,tag:UJ0iRLUVO8WkLZoGhG4FVw==,type:str]
    email: ENC[AES256_GCM,data:epbkGJZfTye0dWA+fVui/6+51tCVHw==,iv:9zJlnJlLj5XnNrbQPQYirhkWigsW9MPhNV5jTJvmlKw=,tag:W0Z8Ssn8EHFCcbMd8UZNqA==,type:str]
    password: ENC[AES256_GCM,data:mva4lgcyFc0y3btKzcvWB7hvG/H5nEiZy66XDUvg,iv:lNPF9tfbXsZG7z6xPmt3QswloMIi2G5NCphlw6YU2aQ=,tag:2IejiYTUMfr57juBsFwyWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd3F2Z2lQeVpraDJVMzZB
            bE1wWld3NEJibXp6Y09BM3N2OGQ1bnpicUJjCmZKRVc0VHFaUXA0ME9wamJHMWh0
            bVVBbmJORisyWDUvQ0czVU9XVTNDeTgKLS0tIHBOcGwyQ0J3dWJLVXJsRmdOUE5H
            VkY1enBqUFVIK3NCVkk0QURQVU80NEkK5/i/ywGjQs7qnpetRL8K/nzk8Z5sgIhV
            3u9X96GW6eAlHff+KcK7USMJ74azvJosg2Tc1zzUwTcjLBDxRB3vFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T06:03:08Z"
    mac: ENC[AES256_GCM,data:oA0ATzQBQ3o9McfY4zP2bwdBrNNBJyOHAX98tSuvJyGNacLIhk6q2Pq0obug1E+x765vNwyaASms1cIIoNkdWZSQpeehXAYr2J7iLX9gkn2JZFjWz6tpP4dmGbTqFhJ8mx5Bx08YlLti0kG2CaBsz8XB38VeFujx/yJMSg9u++4=,iv:rDvwQDIiBA1/5C/K+YjEIt9eiN9XcDZUC+J4KYco3dg=,tag:xj9CMhwsM172A4yo7rfWwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
