default_config:
# tts:
#   - platform: google_translate
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
# frontend:
#   themes: !include_dir_merge_named themes
# ambient_extractor:
homeassistant:
  allowlist_external_urls:
    - https://ha.akudanlasagna.online
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0