default_config:
# automation: !include automations.yaml
recorder:
  db_url: postgresql://postgres:${POSTGRES_SUPER_PASS}@postgres.database.svc.cluster.local/home-assistant?sslmode=disable
homeassistant:
  external_url: https://ha.${SECRET_DOMAAIN}
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0