---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: home-assistant-config
    namespace: home
    files:
      - ./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true