apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-postgresql-secret
    namespace: home
stringData:
    postgresql-password: ENC[AES256_GCM,data:fmieDte9VdjDhDQIIunyxDe1N/rz66SbVdbJ8GZQf0Y=,iv:/4eZ/YF2AlN9zDU1nbF8k2lq4IDwACcIYjvFBRLqB7Q=,tag:Q4MkWTPhfIaoYCYgE1EFQA==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:3XYC1jBpaBfSzPdF1oSXmwW2dx7dprgCm5mgX77gzJU=,iv:zMIkT6seH6fQKtcitdwPlsEL7XIpHCY2l0+mvBT7t2g=,tag:gbLveI1kBkheLitdteFCuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RnA5cnVnSDlVYUFEWWpJ
            enUrWGs4a3cvdmlrMzZVS1ovK3YyM3V6WW5NCjJVNEVhZ3lQNzlzZlRwUzZVRUov
            cUxTZGx0cHkySktMZUt3QUFwdFBQNXcKLS0tIDgyMXUydmtDVXJhZ2pxSXM2YVFs
            SWxFc2ZkUjN2MExvWk0zUHAyTEdSRzAKhqUwTbJFfyaRq3KpWvt4NPkNFV3hyUBm
            4UktlzI4Dcxll8bBXGde4t4mVhHB2MnlKvguieyGzZ8wEkSDl5Lqjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:53:44Z"
    mac: ENC[AES256_GCM,data:LpFBau9apj1jRuUR9zCp4CtgVv2cXpnj/eBuoDyiZE4B/fTjuncLI6/nQK//E4o+KMaokIr9ekkQhrUqTLpmQpYBd2iw6XMpxhFQzRLC9kEFApw4r4Bu9qeEf9PuYJSYSIGgx3BwGD1ZDYQGYcKO3ZAibt29hWhL/fQm4CRE5U8=,iv:pBt5OSJhj4UB3ao4zpRX36Gw2u5HKuL8juiyDjOzZjE=,tag:fL0HO5VW/igmwFyYw3MCDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
