apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-postgresql-secret
    namespace: home
stringData:
    postgresql-password: ENC[AES256_GCM,data:ccTWzxwvbrvzUOTKvKKYaoyXR2zrkXrhlJxEWf4ZmlA=,iv:RJVgtYbStJyPivBSz63tx4h/yNPxb8txpegQH0y9U9o=,tag:m6T+sc8xcQshsSxso178Fw==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:vSKKWUi3o0snzBi4XHYSZGy7l/n/Bc6DIgu5XjZyz3s=,iv:KCMvZSRAi/w7BYyYfyqbulxCqgLGEOboEWyL8eZ2rBE=,tag:iEdF8c3q77AQnLwkYNQ70A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdElHOC9scndGNWRId1Ey
            RWd3VlkzT3pOTzk1RWl2RExTbDN1ZTdTZFRBCkY1eVRsK213UWVTQUU1T2ZIWUo5
            ZzhYU0syeHVtR0pwdS9lTXJtc0VqQncKLS0tIGhCUklIQkpIS1RvSm9vLzhSQXht
            dktEOGpWN1ZuOUc5WW0yZjNuUldvQkEKv8OsWycpvyQV46Pxeu0oPwZofa5eaFsY
            9p4rS7wVpD1jJV2vhLuDvmMQe1g+y5BVjzAmukBohJkqv0SjZCGVKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T02:50:40Z"
    mac: ENC[AES256_GCM,data:+EFJslyqh+F/xbYAndx795B4E2powAD6d4316aH+JPuiRzdZ+1ipGg2h2j6zrhYlz7Do8tzV/SQgeTBm7ekvSpjJQ3WGVkgM5vcH8/Pd5SJaRTWCaMW2QIMuRtsK5yw5SPiSx5MzaJ8eSGVd9hsKdxoNe2Hbj94AEKWMAZtgIpM=,iv:jIAMeBFYZhBZIWcbAjfMQFVh/CdcWiHF9smhFLUd3D8=,tag:LTE1rjoa168Qz/zRqoIdRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
