ansible_become_pass: ENC[AES256_GCM,data:eMQd1VPQYMZ/wh56,iv:oJBcdFEYfnA+s4BFakzjbhDwClSoGbP0NGTmtpC/j+E=,tag:5KQyLvJIPTr9q3R7cy/o9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN3NxU2ZWR1ZEZzYrRnE3
            Z0NVcmR2MmxaMFVIVzgvbjJYdVRRSWJXVmk0CnZXbTFIS1pRd1ptQlFHLzFvTW1K
            UlA3Nzh1TEVrWGpwWE9CNVVWTE1MUUEKLS0tIGF3Rnk4UXdVblhsdWxIWEZBc05C
            M3QyRW4rTVF4Wm8vRHFxekt0OFV3TUkKxU2R+yC+uZMoHUwWDPllqmsZF2Ye+7c3
            R+LU5rrrS/7Aiz4qy7qvESpi0FCQm0hrLiqE7p92StYiH195DKz5Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:03:23Z"
    mac: ENC[AES256_GCM,data:LFHDrSuuZg/76INW3OvvDQX74+OCjcy3MoWArLOmkqL47ANPTO0I/c4Z6rMJOV0ZSkMv12koOK/hGCqkYZossnq4q6x5nxvDi83NkE93tPxyww31IY3MrCkapv2Ir8oCHZjjModd+hYe8RzzS1m+ooS64w5SB54iNtsEnjI0uIY=,iv:13zpCni7j2pm13hUpqzrEmWgAWWQqP5VLbbvNF/YK9M=,tag:1pVHvj70qAu5DVquec8ikg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
