ansible_become_pass: ENC[AES256_GCM,data:toC39ucg2GJOorjZ,iv:unMexegHlLaFj3f/4+5yTsWiOGE471dSbPco7Org/HY=,tag:NZF/40Go7WSkWr2wabiwjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK08vNTFpS1ZWL2tsd2Z4
            dXJTYmN3M2dLY25YTW1GclpqTEMzNW5RcW5vClIycDYwWnRVNExFdmh0SlFwNmlO
            aGY4SElaWi9GemltYjhualcrZ0tMb1EKLS0tIERhci8zOTc3RkpRU2t5Tkc3aEVW
            UXlpN1Mwa24xOUx5VUVMN3RJWDc5NWcK5mdxMrIX0Prqim2m+w6aLL5S9gBYugKi
            lzRrJzu51tqeUwjoZk6KOHlo9km5rdWkXlJgLrdEbklhbBIZXIWxeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:50:04Z"
    mac: ENC[AES256_GCM,data:LdayDeHx0Bydu+sjm7z1tPfaq7m1YIjn5SXL8+8UWv9P9I1O1Koei3UtZoeSwfHRw+NJ9fm2KhDy2k2I5UshQLaDG6qK3eqzmKeAYP0guU3Mm5SIrkJv1TRGwDnZGz7+O18MmJPSxHzfw84/pFjxyKpWpw9U+rb3NFlmmY8XVdU=,iv:/xG+vWNfIKizHJU0al8CNyInCmZZYtp1fAjiWFa/62o=,tag:pM+AKLbfvrCTublSK2MM+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
