ansible_become_pass: ENC[AES256_GCM,data:9TlNT8srINiV1nqc,iv:fAWUExuJ2v4fAvSpo0TQ2kR0Xyvub3j1OA0O43vK+Go=,tag:fOt3VNkMpiiPLkDmif1mvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZU9QL1gxK01Nc1VlZTNB
            WVNIVVFidTFvM09rVm1UWHpBRU43bGRiRTBBCnpkaU5RWm9IZStvOU9xbVg1TFUv
            YXc5SlloN1ZscFdHYTY2SjNkcTNHcjgKLS0tIDVhd0RzVGRzdXNFTTZTSC9nSENj
            MEszS2c1SkV0WStsUEVhdmRBa2k4ZEUKRzh3x5oScDwe9DBXQjH5lCI1mITt+pK8
            RDWAP0jxovNpDZvyUlL38gJjPqsUhM3wYNnnLGGJQLgHyMW1r6HveA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T07:33:08Z"
    mac: ENC[AES256_GCM,data:s8wK6ob5dYgUEec8q9pjk/pBbIavCv7WSoyuW9un8RQyuGYQuwIfHQexYoKaDpriaVAmvtDpkIH/Lqsn+QMUDTQh5fzox5w3en9XjPAWEd/xATIUp5Xe6jR0CmBX4qgnccEVKpLXqd4BiHtVziBx1xgHSkJ0tOSxZ/nas7xHfTQ=,iv:pRYX6xliYH59jQFIz6w1M7DZW2p0TcRku1E4W6aGRvk=,tag:j2GyT4sEGQ6LXokNOHQltg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
