ansible_become_pass: ENC[AES256_GCM,data:wEfM4LbcldMh4QZN,iv:DqktGOw/VM6+yykl5f4lhAY8JbT3EbT9VPVhY3Xw+UE=,tag:ypksrFm/a/9I1aEZ7Vu2RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncTVoSk9takNqK21GY093
            SVlSZmRLbGVFcCt1SXI2R3VWRldQV3lQK0gwCmFkSGwzekVmU05tZzZrQjhLaTVI
            R0xuSnhCVnpOeXkwQWFTK2Z5Q3d2aU0KLS0tIFNrQ2hSTk0yUDBUV3dKa0xRTmpM
            TG90K2o4N2xSS2JnU0FjUThJMVpWV0UK8xBjx0aKxgldz3+/RIX69DHonx951jzj
            +nw6OxYMnN9MNAW9jxtGGtcR20daG3lvU4c6GtdhHr8G2qIWQrq90g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T04:36:05Z"
    mac: ENC[AES256_GCM,data:/x2t0qJo4crGE/QAmYdssaj14d+j96s4OlBEz2oj0ipZuFHGiFbLBfK9DSQFjHfKKXYvrS/2I7gQZ9QiLI21/oW6ydVw9h+Qa34iiDE723as5cM2x2hEk0+2z/54PX3KfPC/48HyPvF9wm8+FmXHVgWtlqc6Z1wTWEFRKJHeUdw=,iv:VSqEaZO7MNnv09f1TiU4pkDNre/yNcguEe6Qxqa6IYc=,tag:g7024B8zbLsnc/+gUKitrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
