ansible_become_pass: ENC[AES256_GCM,data:FBqRShlF63UvjXTE,iv:Z3xXv1r6gD+h2WcFMg6o8U9aKf6czwOcZG50Y0vXRB4=,tag:+GV6zHgUdPrEnygfBWs4kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVzFlRGJFSkc3RGtiN2s1
            MXJaWXlOaTR5aTkvclhRdFZLUmtrZnE0bENrCk5ZaHZoQXNHN0tIZE0yRDcyQzhM
            M0FHNjR1SnJONVlFNXJjU3NPeDBwd1kKLS0tIEtNWDR2TmgydU9iVWkvWkJBUTlr
            dC85YTY2MHR5WEJwTytLK0I4MTU5blEKNul4Zl/ytbMxA2laEGCRnY7UYvUJAt3Y
            eerCAWwRibP3wBdCzZGdeRLUt/iAXHTfcQe9Zz3e/E6+KRsrENre+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T02:23:38Z"
    mac: ENC[AES256_GCM,data:/BrTzYNYweuT2+HLM9gizITQ1ZlPZ3ETlstI73jxvYQPKX5wKtABhOD0b62tF9IVb9ybXJyeSJMzh5gxwxiZSmdp3w3ZnZAUcs4b5QGlaIQfmycpEGErzHpRsPFuC+TFlwE0jkOeKv+mhlFNzOeeYp8hogTq9PJ8r4paKnWZdn4=,iv:lYQEpef1J662yN4hNkoUN1rPi/7NwHhT5JshrxaK5SQ=,tag:0UX5gxT/vBLY501RhYncXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
