ansible_become_pass: ENC[AES256_GCM,data:O10OOfosGrMUQayw,iv:Zd1DBJlcMTcEW44kZ5hH9eZd73WNwBs47jkupmwUwUc=,tag:fBzmJ3Met9nrxxMIbqFyhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka3pSRFlQWVNwV1lhdHN3
            YWZpeVBoclRzdmFORHFFZ1g2VlVaYm5hQ3pVCmlXOG8rZEIvcDFGdlk4MkZjSHBM
            eUQrWTNJMDUxZDYzeVdGSWhUSUdNLzQKLS0tIHdpYStseW9yVi9XdTMwSEpuLytQ
            UVIyaXd4UWZXYXFjNE1Na1UwbVdQc2cKv/B6NRW21Q5MH+BJSowSv2ZeaR0f1QPq
            +Td+N8dt3g/1Mr3LVQGCkSLoWZlu3n9mEOZysshUx53s5ABycnRmWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T14:25:28Z"
    mac: ENC[AES256_GCM,data:d6agAuc0KOaxiFlROJ55e76JLLzYSqDbpw74uS017cND4ZV9Ql4pDg2ivvEojubkz5nHGvkfefx3nb995bcZ9iuqVolrjLeJ9SaAMvgZaoK8gN4owmISsTQ4MwQ++b7ivqKJqrz/oRqqXYR+8ElxBXNHbnahxXlamDZgPWvzD4Y=,iv:LYTVVDDOFJxr60sAx6Lq/aEWZcBf3LBj9C3+R1vSIBk=,tag:gG1ds8c6048Jo/jEpIzCmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
