ansible_become_pass: ENC[AES256_GCM,data:l8lKG7Iemo0XzgU4,iv:LMg48pRbOzSqAEOElDOkQ3BgueQDwYbr+NcUdXYkCbw=,tag:EqaxnR7e8lKiD69QoGE7ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZllIdVZUeXpQc05CMmxz
            aGFNckpuUW9PSVF5YS9ZL0c2OGJVWXJCcDJFCmlkTnV0VHhlYmJhMk15TkRCNjhF
            TlR1ZFk2MjJJZ0cxaVRtQ1lwUnVDREEKLS0tIGkwVWF3MU9FbDB6bUQrN0UyQlVv
            UjJIaEt5RjVaWlh5R0lHY2FwWkxyWlUKgAiFgeDtAKo+mgaNN2pL3j3zSB2nXSxb
            GuuB8ff1E3NySotfyTOA4G0S5xC9eHjknXp3wXStyIB65f/4mhmF9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T05:10:05Z"
    mac: ENC[AES256_GCM,data:aQkN7Rsud3NXTv5L7S5wYZSM3gez1FScX7O8mdUV4pshnQmSAQixEwaJmB9fFghrJZC5t7vPlMVLOMBUSY44hkLRSCBj1DOMc9DO/0a8smgOaE1sozqaCWgThXEt1lu8OxEd4GDyKsbgG64C83sMUnDCrBojvwArah4i8AF4alY=,iv:YWsA7bCCLamdk9PXKUDtvVMqSIAfjf+sEb6zubdrymw=,tag:l96ANBzq/D/sfHx+Yc2GMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
