ansible_become_pass: ENC[AES256_GCM,data:xpy5D3e598B5PhDh,iv:6XuMQI/bZrVUPUJIOSKZ93esvCsEuo7rtBzkFfduL+Q=,tag:ep33lxEQOAtyseUohpks7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UTBWWWw1YXUyWldISzFk
            MUZ6NXRZTEFBMy9yUG5PZzBNVGJkbXZqaFRJCnhFdDZraGFlc3hHcFp3Q3hNYXFm
            WnJtendJaklZOWV4R3c3V05BU3dDVjQKLS0tIGdDZXk0eFdaUTlFNDlpZ01VaE1U
            ekVzWHVTL2hESXl4WFR4TzdHRStYL1kKhGS9NhsyxZRBFsB07IxkfEySVdDW5jlM
            IojKIw00nF4bex8Zz3xkf52L5Py9CBv2xOyVsRZd0JUCz0t3noxbfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:04:20Z"
    mac: ENC[AES256_GCM,data:QuEnAAMl4Eu4uWmagc8rk4yRFU9x+c5S2NXfIxTVyNR8U85vb7vrYPT93pcfpSDsZPthjdoD07dzNUoqNnpBG1ZoCIDIwWkA0idl9CE7+T9aXCpcyoqBwELOSfPCJu6CpagsW4iEdPlcTXVf15wXe9U8dXc8iDF4uG4+U+91Zbo=,iv:vXMYswPKs8HQnHZNTmPali1Jx+zKYyNtlOz6btwGUvc=,tag:tC6161nZaFUPky8l8RoAXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
