ansible_become_pass: ENC[AES256_GCM,data:Vx3OsY4tnv4AeOQA,iv:PwiRc1RvqY9jxV3NbKIvXzVL6hwOExWGycYlbMIi4AQ=,tag:SRaFMTJaMX7nF4Lx0qCeIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZGVSc2FRV3cwVWxXUXBZ
            U0d2RER0eHcwVWFuVTZIcXA4REsxajlSVmpjClRtdHdZVC9maFgreSttUkhicDVI
            aTVuQWFESHJIeTZMZDdFZVdQY1NEeFkKLS0tIFBYMWZkUlBESHdwbktFU1QyN09E
            UDd5VmdyVlVQTXltUkV3b2RNcHRQWWsKtokvO9VMA4mgBYwDVf1FzHL6FYabzxNl
            EHF1Xxy4de7k+L4TPMf0rOuO27eHaHPfouc00Jz4O1B+EWNEC99PCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T14:09:00Z"
    mac: ENC[AES256_GCM,data:6JsMeRV4/vrK1EMqM7qM7eK1F522LGHoEwyCf32uJfvHR4iBYbAMutAE8t3HeV8YiiwVwHRZe3CL1WkQGRmf7+RTMF3NBPj16A3qfHYzAWd1mZcmAM3TEX2VflKYnr81jXT6i7pLpxB+kFjMr2tLyjwfLH56ChX56z3SaWrlnYo=,iv:Q3rxbEMCZWYyJwdmSfGJisCDWX5lCrVjaMnh4lb+w+o=,tag:YxLWpRQaWb0n01d3gVFaqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
