ansible_become_pass: ENC[AES256_GCM,data:g7OnyHiR3fLkbSjK,iv:xWqZK8Qw+UGUMPmE9ik+wLL1MlXT6gWxVCWdlgsWlPA=,tag:5GA1Yj5hC1eFI0CPd1Xu0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cmVrV3pvTjNkSTVKM25V
            Z25QV0tGYjJxOEFNQTYxMGZTMUFEY2YxTDJjCkZWM1dUTEE3STcyR1hwNWhaelc4
            SzIxT0dPVnE2M2JxcVRhMGhmbC9Dc1EKLS0tIDRuckQ0bE5kTnQzK0ZWZXl2RjY4
            S2IzS2I3RmswUjQ4RlpyTVByNTdJR3cKNYFNT3OY+vmkMptPBZcjQYTjIbGjQ7UK
            kF3Ubf1cWB68KRBXPfjhyMyL4upRpr/jo/5Wvx2woX1NFeBuYYyNVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T04:19:40Z"
    mac: ENC[AES256_GCM,data:yLl7NBhp3swRALRSiPV1qaQa9FEEtDIlWpKRN2sSuHBAHUfNkS7hS6NqMB1+L42XGQcwTDehRH1Upp+/bHpdlFrghke8Ok8+tehXSn++YeWn7wRv/hyL5uKfVsRy8EUotAdopD/u6kjp6Gp77DH9NlHruywyetOTbMYUJZzQnrk=,iv:I6q/9/zvN8Vyfc08O9u92REz/ojurrVFL4Ym5/98O6s=,tag:fqBkVNIax/VmSZ5Plpfp9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
