ansible_become_pass: ENC[AES256_GCM,data:SGaCSSwDATB37Yy3,iv:QHCkTVkwcTJAUKl37fxM5xirQf01jh1a8GqEfWtvpiw=,tag:1WJ7IfQbvCIsKfhJ4XGneQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRjFkQkYyN2lsTFNpT3Bx
            ZElob3hlL1EzMEtBVzNPU3c1U0tzNzdtSFFZCkZSQWtpcnNaUFlkWHNXL2djY2hZ
            b2ZINStSTWI4NlVDWlR3dWJCVVJ3dFEKLS0tIGdodkpXQUNHRFc5RXNLS3Q0MHJz
            b1Z6b0REeW9rNHlkcFNvRlNBZkdjYkUKXGcpWngq0ZignDjsIQC+FtZloFe/r3Sx
            oUuo+UpNs2ZjjQsPSBNox0TwHCp4dHMyh5amaBW0oa0q5efzjK9W6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T12:51:06Z"
    mac: ENC[AES256_GCM,data:xEwKA8XKZ4LDMXra91MFyBYxQN8IOSkSQCgH1SDtpKWGi1Rgf8PF5ZwPBDJXcTO0y1GEthnMtGqLgZdw8VleSGNiac68JvX6r99ELfQmGmOenROKRoPw8vId+EbQdFZS4FFUS+RPMqjxc13YL/YlCt5niKIUwI2NcCzCoNSWCd0=,iv:qBFVymNo7BL+jp3Ix3P4RfIu9R45sYsdwNexfLGmknM=,tag:mRwb/ttokMUtyAPcUndkEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
