ansible_become_pass: ENC[AES256_GCM,data:bNXHp0F8D8sfTnqY,iv:ypZFsyli3sVIudWmyHQafpi9nI8RhYz6DzRh1OgqjTI=,tag:MqifchbiOgpcf36giEmHpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YzY2WWc2Zi9YdDZkUm9K
            QzV2dE9UTVdQZFIvQyszS1NsMlpLS01DaFJvCkhqbkVnK2YvNmxKM09KbXRIcnJl
            dDEzWGZtVEFLTC9qbUR0ejZWL3Fna1EKLS0tIHNGbWFNN3prQ2JWV1d6b2IrQTNs
            S1N0VzNXRTdXKzhQRmZPaEJFNUlqWHMKgQXiw679hxInujulhTiq6oG1hL9oqcyP
            1h/soEACQy4udMFEt/cADhjAOd9C8CFK+4m6hb+ottKZR6Dl9qDOYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:44:42Z"
    mac: ENC[AES256_GCM,data:mAagWKqnzUZhdmCxK5CeP+Bt06y3LXNLmy8wUgK/EUTLC7jTBhcwH1mAzPJrGFL/sMimWsH/Pwx7z2Df3ivRk1L3NduSR9mJ6rYiIQ7tulJZRxlNOfUdN7XGuo75JcFu/tup6SbdWtZU9O+W5RdcJGv7Pw/124sMVZCdT2U6OpA=,iv:r5Gdl84qXhkgA7KmT9FaMC15clB9QsO+kkv4xRxtp4Y=,tag:NtyDg30mbytgeGs4+l6kvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
