ansible_become_pass: ENC[AES256_GCM,data:d8RAPjCSORlyx8Q4,iv:/ryJYcZQao6uc8+rXMp21Vk1VEjD3ScdZJUNtGzDUXY=,tag:bG0SQ/esMiwh7haXt5m/gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSnVxK1RUNnJOTGtXcU40
            YUt6SHJQUEpDYm1JNTAvZ3JxOWpsOFZWdUNBCmZCNkMyUUxRdW4xWHhuTXFIWDQ2
            VWdpVUhnWnFsOWhDVWJEcUR0Q1BWdWsKLS0tIHArMTVaeXgyZzhINlQ5VmlJeGV4
            a0l0WEI1eTF3M3V6MGtZTGdOdzJyN0EKyn2bSDgPWpuRssDDbRmu+bPMmr8GLga4
            FTqh3ET6IRAJ/55+9tiPz7vRDqlSZe80ttO7k0cn2mefU/fSQFGPRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:44:44Z"
    mac: ENC[AES256_GCM,data:17GMsfZXwes7PJboy3E7J/C8zqwh+ldAjcIo71TyFRQsFfztpYFPwE+BBC+Jcu8EpnRasnOKfJlu9ZfOZ7SzcJMOTAQZWFcpLORt0FCy+WxkE9fpbomqoHcDTLE6H2EA8/7VC5EDKIRpIKECsT9D+gC7PnKlmX7evjBC/wAwHOQ=,iv:z0MnMzFLXk4YNiXYrJivZuCxZx4uiBNsWSiiqy6+0ng=,tag:Qq3n/o9raPyPNnj+1VR0DQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
