ansible_become_pass: ENC[AES256_GCM,data:n7vI0HP7s3mliook,iv:8BQa+ttPkRN+ZzABGHakP+TMaO9gM5q8EevMckPK4Nw=,tag:TfITASR5WhtcpItbMqlt5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eFEyVjFXK2Vob2xTdTRH
            dWM3UUJqY3dyMEg3dmhLd3V6WTdSOTE1WnlnCm1OTjBPblJHNmJMaGlZZXQ2VjF2
            RTlQSVJVeVorOU5oaFB3dC9PbDNOUDgKLS0tIGxxcE5PTUtFdzJPWGRrb3djSlFy
            QmdsTjFTNmNndWtvRXVlajRWTkhFRFUKJ5xXGGRQDCFYs5zCs0YwKCyudrAIEu2Q
            38u8NApWUYx9SLbWiqq1G862sIIWhRSD+qk7Yixt8IQqFA5dvmOzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:44:41Z"
    mac: ENC[AES256_GCM,data:HbB8C/iu2Kt+H9vSHdwscJ3OO73GQ8jwsW9D1j9WVqQqVhv2yZghGk1J5pjZPujhc0YfKZF40G6Uj3srT9Iavku7lVxwpNGnMp1SMJP/c7WQbmqanHtLgNJkmmeV/wTFK4RySYf8pN2zkj5quxPMXVraGK4hZ59eirF9snu1gfQ=,iv:Zyj19uplmD9Na+uKjAAt1RQ/pfdwDblgOb7Cx6JxmbI=,tag:QrLWOEz80ewQi7Vz3rPu3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
