ansible_become_pass: ENC[AES256_GCM,data:wu9azoD32PIvJ4ya,iv:rm9qwTCwwPU4J7ZQd+KGXNal/rB4V11GyJlqUakWrpk=,tag:+18YGpcK0soMZP0qfyw8mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTkMySWQrdi91RnR2cXNN
            cTV0RW5nWnQyMklHaFhHRjdaVWxrSVo5akI4CmVXV1VueThIc09xMWtjVDVISzlh
            blNRbndjdlJCWCtFbnZja2tVSnNlWlEKLS0tIDA5VkZISktCWWxHQndDNFJuN0Ju
            WVhrSmkxczNSTmh5Mk9KaWFzRzFMRmMKBgxzFRMn7FuRo3iBW1TeAzU9FfLyHtfN
            ZWkqjl+zw2BqmIxA+MfoJdxmnvhyZw70maVhxwYcYxvuq59xTmNCdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T12:10:21Z"
    mac: ENC[AES256_GCM,data:k7Qk7D09nRJe2N1bjAAN1e1UMRWpuAvUQL6VlrfGNZkLTiGM+/fGuuVotlcwe4YypmzQMjNCfogqGL4sYPC17J1FUUVG1T45GomqChouLAxPxsPDbFcLyZ2834lkTbn0oJVxw449MLiiQj2XktqnvEo3eKW+pKXyd7ljJuOcF/c=,iv:lyxQYNgXbDF0A8mEPxOUpT2YdEgVvkEGdX2f/VgVEBA=,tag:uPd+Q5KhP6ciZEgktXLBPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
