ansible_become_pass: ENC[AES256_GCM,data:occUt9a4nN59HLVl,iv:jleRY0L7Tpff3+jZRzj5mj3u93EJ5+7CmCZy2qa4IPs=,tag:7hpNC+zFz7cHx878WbIhmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVM2MlJlR3BEZ256Rklx
            Y3FhaHdZcmg0SWlKSjRwYklQVFV1b29nTG1vCjY5L2F4alFSaUlRSDV3ajFqampl
            ejlDZlNTM1ViOER1dEdhbytiSTFNREkKLS0tIGhzbHRwaHRsS3piSkVwYWZGOVZq
            eEpIcWg0RHRTVm0xSUhXdHF5eE1ibG8KYoZj+v7jRAj9YYnv8n3XFZfetQ2e9SMZ
            IyVgP4Uh+md2YhRDZ/1FGqWqoWwtNDyUY+otBSTj7/GDk1Fq/Pd2QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T16:13:40Z"
    mac: ENC[AES256_GCM,data:iKQxLJ918Tia14pYgHaoZEc2sy6EKLT/okk0X++scR9kWCJZ0mJUAy5rk5LuXTIEvxAV9MTcpNNO+6U14jG9qNhwz7PTXOsJpDbeLrHvVnDAffbTkC2aVslJ5lH3Wc2/QGjBsq8ZejuZxoZz1JVxBKWOqagsYCsC6E7XCB3BinE=,iv:yDVC3UJMCeeqeYsqgyJw86BhSUUWxtJL91mMUQ8ljgQ=,tag:PgPH7q6rHh40OasRxn9maw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
