ansible_become_pass: ENC[AES256_GCM,data:ppH70Uxg9iZo/kY9,iv:KmaA0pQFk2Mr5F8oEv/bakgVDr0vSqN7cRfsXa9oW9o=,tag:I3NiIMo/xiJJ822b3j6cIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRk5vdHpxL1NsL1kvL2dr
            bkZlQTB3NWNpUEp2eEs2M05McVRVSk1Camk4CmRUSi9rODBDTGRnRnJQc05lT0dN
            Tmtmdmw2YWRERXhRbjVZbkNDcXBhUkkKLS0tIE90QkM2TzAyR2hudXVaeUVjZEE0
            bE9QRk5teDZrUVhSbGUxeGxMaDRmcFEKFbRsQFGgXW++oPcZZawcPkzkjbpgoqfi
            tJZ1N+FOJBfQgoo1NAVIvvYBUU4xsw4IcOD/6Os/xwR/zKpX3qU90A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T06:44:36Z"
    mac: ENC[AES256_GCM,data:YZmyPr+Be7lwvrtNWZ61Gdtrdc7VQ6x8u7gwgZwZ4UTiOFj9lF8tWCx2UAjh5YPEidzdtMXG6MmPFGkyx0bQrL3cVkddXubJpkcgJvjc6WIGD2hCzQcTasFAfnHWpX4k5p4MqjtY52+frmSMonFWIiwoSh0hTmL1XcoAqwQPrws=,iv:H4uuR3lMu9i/EGnAMSIlNk18fDF/0xUg4PaAsHkNoho=,tag:ioehfu124D+UNef9yzi+GQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
