---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      chart: uptime-kuma
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  # dependsOn:
  #   - name: nfs-subdir-external-provisioner
  #     namespace: storage
  #   - name: cert-manager
  #     namespace: networking
  #   - name: ingress-nginx
  #     namespace: networking
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.21.3
    env:
      TZ: "${TIMEZONE}"
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
    # podAnnotations:
    #   backup.velero.io/backup-volumes: data
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "wan"
          # hajimari.io/group: Internal
          # nginx.ingress.kubernetes.io/server-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter
          #   '</head>'
          #   '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/uptime-kuma/${TP_THEME}.css">
          #   </head>';
          #   sub_filter_once on;
        hosts:
          - host: &host "status.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host