---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghost
      tag: 5.38@sha256:0ba58c36c53813933023cca728a026f1f9f1b129364350021fdf6703ae148829
    env:
      TZ: "${TIMEZONE}"
      url: "https://${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-mariadb.media.svc.cluster.local
      database__connection__user: ${MEDIA_GHOST_DB_USER}
      database__connection__password: ${MEDIA_GHOST_DB_PASSWORD}
      database__connection__database: ${MEDIA_GHOST_DB_DB}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "post"
          # external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      content:
        enabled: true
        existingClaim: ghost-v1
    mariadb:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-mariadb
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    auth:
      # database__connection__host: ghost-mariadb
      rootPassword: ${MEDIA_GHOST_DB_ROOT_PASSWORD}
      username: ${MEDIA_GHOST_DB_USER}
      password: ${MEDIA_GHOST_DB_PASSWORD}
      database: ${MEDIA_GHOST_DB_DB}
    persistence:
      existingClaim: ghost-db-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-v1
  namespace: media 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
