---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghost
      tag: 5.38@sha256:0ba58c36c53813933023cca728a026f1f9f1b129364350021fdf6703ae148829
    env:
      TZ: "${TIMEZONE}"
      url: "https://journal.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ${SECRET_MARIADB_SERVER}
      database__connection__user: ${SECRET_GHOST_MARIADB_USER}
      database__connection__password: ${SECRET_GHOST_MARIADB_PASS}
      database__connection__database: ${SECRET_GHOST_MARIADB_DB}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "post"
          # external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "journal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      content:
        enabled: true
        existingClaim: ghost-v1
    mariadb:
      enabled: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-v1
  namespace: media
  # annotations:
  #   nfs.io/storage-path: "ghost"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn