apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:XQBwwTK39blfrUIy,iv:Y0VSfplaRBpdg2FfcDzjTJPxidJLJMP7tpobQx6uvbE=,tag:ZFKjbCWIA7RfRLgI8NjquA==,type:str]
    admin-user: ENC[AES256_GCM,data:IVzt6ko=,iv:/vViArH9nj+BzVPd4rAsbdhZKW3zIzOr37NhtKZb20s=,tag:LNqYF3XnNztd7PLt3HLE0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobXRxZVpzNEZmZW9Mc0Ri
            SENGaCsrRktDMklnNGQ1akNtSTJuT25WeUc4Ci9vTXBFR1FIQWdvSmRqQ244aGxt
            anl5dy9JdFZsMTlSVnFmN2xOTkpCLzQKLS0tIEtCd2tJZElEaGtQUk0wdmladDJU
            M2ozSHppSWxUczVrVDllM3VwN1gvSEUK9jYSN7rL8COZZmdLncNHXTX9Yodv6GHK
            nXW70Kpaj5Ux9ZLhLh5WIsKXENqSfjaENn7px5Nnwq3Xqj5aPG1z+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T16:38:52Z"
    mac: ENC[AES256_GCM,data:L6HJMBPL5NUpJxEmqwgn9TEPmu26K5BTs/nGWJdXiaRK9cc8z5VPTuO4+Ia1C0Rh+/eSEoH7Gr92K0vO/jHyPt8W9/KgRLEsyu81vHWuV1p+1oTq3hSE26QAe+YuaysxwTCuqoXmysBB8LVrmkVNrj9ug53ofh4fIFYUeGBQaeE=,iv:6EHWUnmUh2xPebC5gDStGzjbH84hlYMcwz6L6b6lDz0=,tag:qzxX91RKx6xYmPVA3yaKqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
