apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:4COKefcVWlcFnhOP,iv:kXFo/ncZ5okbmeoAloH2sOb9Kvza0EsaL81xiy/sKX4=,tag:iZu4xKlC3BhsXVll7fc35Q==,type:str]
    admin-user: ENC[AES256_GCM,data:pvLkjhc=,iv:/sY+v/yCS2TgWJ8fqyy00k3ls6B/x9m2rpfiF+0Aia4=,tag:HMvQTNpWlWjfsLpqP4cj8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc253SFJGaHpQTVlpdzIy
            OStTTU8xUUw4ZFI2aTZsNTVWeGIvaHFUTkd3CmI4UHM4ZS9UckIwSEtyMGhuR3NO
            djhrVlNyYnYyYXMwejl4SldTNGRva1UKLS0tIHRQL0VKazQwcnhJbFF3VGZjaThC
            eFhucHN5NlhwMXJvQTczaFcxbVZWVmMKbKWHxw1mwdew/L2jQy2FWZEG5XUpT6Bw
            2StDs2VmAoUwgBWQJcWeeox4TkOd3o8ojZoiB6nuQ7k4/7OdxaWQTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T07:00:01Z"
    mac: ENC[AES256_GCM,data:o646HwE6CV/+xFy9whbX3F04mpiTfEHME9/4WTidGiJpv/3Durr5pj23v5VCBPhZI5zYdzyqL1L+jRRICTZm+/Vo4gyamF8mTHwwJSozetAvBPU8kxRUsxY6gv2PQDFHlh9HWdWP1BtM7wOTgek2hs/l7As6Ze8amjPdaEeDqW8=,iv:l9IIpieLP71MsOq7CtBpFFI70OG5XDCnZn8nJxQ4OCE=,tag:rcR2zIl4fdG4QbYNQWswbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
