apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:8qfGW6P6P92adxC0,iv:tq3fgpIfJtygEtLqRYd+1/sQHd7XGd5ylfSJzKBnL/0=,tag:VMI0w3Daeb+MW7iTJwfg6w==,type:str]
    admin-user: ENC[AES256_GCM,data:qivuC1I=,iv:ITCG6Bqd1LoMaUGPULqXKOiuR4f/whE0jEBOoyqRQqE=,tag:xI03IVfcllm5fPJtRnvmQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWGpMckx6MWV4Ty9SN01W
            LzQzWW54M0lHbnhuWVlUc1gwdDZ3anlSc1drCjUzWFBxVFJzNzlLdXQ4UysxY0lu
            Z2FTNXJValhIL0ZRdFRWZGZQNEdRdFEKLS0tIDF0cnY5RytxSXZwaWlSSmNrekJ6
            dDZwWWNGWmRQd0hSRFRib1VOQzJlZGMKF6N3rbI2NQLtxKJJQTMZPr7q50xWkPDx
            8rTluwAyV5YUYBIoiDvDWDm42Sgp+OjZ9U+tMY28xCTY3dDI4HTKNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T02:52:30Z"
    mac: ENC[AES256_GCM,data:vpdp563iiBnFdLlb+8RS3dXUq2VsIBaJ1/HEVxkGo7B7jaAnsicVJLYQ4GoQdcbb6Etu1vINWOgKR8AuKx1PGm+tdXE95zi8m9VgjlWTvBsJho5J5U7GZWB+ycSQACu37TfcDaSIaMCF96xVSe8/Xaf4v/e18Sz4m5oHVInjLJM=,iv:4ujjXfpPRuUMaNIDmOI8hnKTRZR1DyKaZTuY+Z0VknU=,tag:jcjqbyrTb6zK6MBSwsFKsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
