apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:FcumgZk92Qw/XjtC,iv:/OReDkiLRE63W3vXOVbTZ5PBubADuSPIBhPUe5/w6f8=,tag:aE6012JnF3xgLsqseJfm0g==,type:str]
    admin-user: ENC[AES256_GCM,data:m9a4YNQ=,iv:OBOMqgypcRbcK3TFOgFWO5Y/HKCnhAz9oobkIqVgOpU=,tag:bofT8nzOD5oi5mvuG5NG5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMlBZY0F4ZTNpVVBIeXhn
            REdWeEZUVXl6V1ZIeDk2RFI4U1duTVQ0TkNBCjNBRS9DMXM2cnJMdWwxZWhtRjR4
            Nmh2RmJZQUE4Q21XcWw3dTI2UE9rQTAKLS0tIGJNSERLL2tTbUJ6dnZKVFVGaFFF
            Y2VmL1ZUTjBNRUdMRXZ5U3owTVIrODQKXLgi9tESYPOp8KAesVfRfl4T1JPNX9uV
            HdYrp5qlnZBTLg/BpdzzM9krFQR5ZX4PnSit8qK8EXMrrwubiYFSKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T09:22:21Z"
    mac: ENC[AES256_GCM,data:QC6wvHwoA2kjvEcDtL/thhPiOIktM+xUlbjxemBaBwyghpRRZN5qbmbgpwlWjkR0rjF3pa5tfaUHOF/PMhzrAzF+pUIyvvZw4Vqsivg/HCSsed7MOP4dg2Dh+Yv+/hsxAOQQu6g6WF/VsHIM81wy0OnA34eWFeX+PiZOVirpq1w=,iv:X83ivByKstB8rAHWkpnfUm/HefCKixNmOsA2F6s9TQU=,tag:/fA5RscQorGGUJZSSOVUyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
