apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:lahVzeGQXs1sxMBh,iv:9iRJyFlYlBk0xamxGY4rykdM0rMuVo48XyrxgUTYf9U=,tag:dGNTem6jo8nlEQk4JQElJQ==,type:str]
    admin-user: ENC[AES256_GCM,data:69O/m4E=,iv:8ctayeMShZtVZDCTh/GSJck07SGGTcHy9ci5GokJmkU=,tag:nnsxTaeSEnq6VW0wjdS0qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndFJwZFBwTG9kOThCaFAw
            SjZibXZhSGRYRGdFaWNYb3lMWlE2ZlpuZnhBCkFmRmMvbTdlZ2V5bEVaalR0NEdq
            NU9ndWtlSENwRHJweENhak41dXZBTHcKLS0tIGNCbFovanVrSUZLT3pFSlB2dWNt
            RW15ZHE3WVJTVC9FYU1iOUtYcm1MMnMKuN5r2mj74t386GEBmnwPwpJ6aQqsVzzY
            /kWbEGJhma+nNIArZ0lj3lN/+6ffoN4VHbyIn7Ex3TjC3TSvQ940Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T04:55:51Z"
    mac: ENC[AES256_GCM,data:G2hy7TfkV85ERnu++GN356aAjn01t6TQYr+jXBp/sPkjcsGJ/QfYt2LC7r4ATrDxNg2haDf18mHV+9M+laiK75FgG9dzqLx0UA+596GwgzHvUNzKTSXu+8rjnL6eJgpVB7MVxStc/gzcPWJ2uJvPTjvR3Dn78/w38bdUzlde1QY=,iv:euLD2VEXtBPx5Z76iAu4aoy9BHwWdTD1W3CHZIbwBxQ=,tag:0MAwdlN3bkpm1lCkq8LfJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
