apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:teGMosfoimziOkq/,iv:M+JOVjtCVq4wSJFrUzvV97XSoO4K0B9D03lhy9iSiYk=,tag:5nX0w26r7rNtOJETfpPKQA==,type:str]
    admin-user: ENC[AES256_GCM,data:yUBKC0M=,iv:d6pfrx/+JpQ0cCZQpBT0qhnhyhq+gDQCJyBe4GirPwg=,tag:YOZuZyowFGQDlWUeeedv4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNEVJZ0VkVStLVXlHbXM5
            eFRqcXBwWEcyU1RFMkNsQU9KYzZ0dnlJd1hRCitnY3lFVWtIYVdyVHppWkZ2OGdK
            NDZVZkxCem5tNWhiQ25lZ0hyRXNDY2MKLS0tIE9QSFlqR0w3WWJGbStNdkRIRXkv
            QzV5N200RWR5ZkJ3UXZWcTFrWlVYcjgK7p/kpkwYHwXbkvV6AUWm4cD159Qpmfmr
            OPtohtEIyUWd0S0F9q3/jzpLDTV3EuzmGE7dP12sNRJrAFPmeClH6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T13:45:27Z"
    mac: ENC[AES256_GCM,data:tXEBnVOq7wwPX0JaOAbXshhGU+djQaZQ65V0sd6xY1g2ro6MzVGJTx3dun20kGuhO0MG3fppA5AAwCMJZ6XvoHpIg0bcXsTkeOlTWIuBql1NlMxY5dmh/9oKHm4TQyiIVfWrGUj51Xr3kxf5l0FdP7yFEkAxj4QJQ1oxLmTRhUA=,iv:5FnsB/0JAPxPzdIupGGGT8MJOrurgTkHNcI2551IHjw=,tag:dCIvet5A5oOdiJSYRk8swQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
