apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/8kgD8bejUDwdZJ6RBT9jWgWmIf+la95,iv:U1QC60f+DxZv0F9KA+f4Ciq1yNvP6CVzJ3TdNhltsWY=,tag:UnMDo4GHhGsCRcaYhQL4Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NkV4bWxtd1VpS3F4a3ky
            MzN2TjhocmJKWVc1a0dCSlBZRDlkeFFjSVh3CnIrUTFRQ1VYcTViTmFtVG90OUZG
            TDJ2bGY5ZUovTUZtWlNOVlJpYUh3K00KLS0tIFRydmN3b0plUVk5QzdpZHl0NExh
            UlRqQUlIZTN6dVNjSGxtNE9BSjkvQm8KQ9C9AR+OKiKA92DUyjZgYdD3JYo1lg88
            Vy6H0ceLm4RBKukVbFYzIIHz9DnTDPpt2CqGKYlqMXHR0BvP0cQUEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T14:52:55Z"
    mac: ENC[AES256_GCM,data:WWUDZJgzwgm/HJnxd0jrgWLN2Bw4g3yM7s3JNx6DxkUhsOzxiOvFjW6E7OiHNDm5wAcL+InQHes9gvP2mALGINB7jLVaBGGXexvu7+UZpCWYRlvSpKZECByoC92yvew4K1r1U6zfLda/sh9JMKQCm+gCBNEmrDRW9B5Z1sO3tOM=,iv:iEG0r5Q+sYDCiIeSW7FjAFsZ4kpz6pq+/VSYljkMNPc=,tag:7H7xLDoya5f/Y9AvgUhsbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
