apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fuabhzgHImPdx71ZqODRtrG+2t7aIpo2,iv:2LG13v+hfqQVOwiTLWxcjRuGJJ79NUdQfg88ydsw0/E=,tag:3i3Ou5kNo1jstuNdr8eadQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WnlmL0RiTm9kRzRBcXZH
            VklJaWpvZWZVOG1Wa1VlUjlmeFAvQldRdG5jCm9mK016a0YrUU13M2NYdUlVNmlY
            VDNmSUZxbmJZNmxQNGRCYW9rM3Z0TnMKLS0tIDIwMW9LUnZPcjlld251YWNQWlpz
            blEwZWcyb05pVzIzTWcySHJmcTZNalkKUD2anwVNnd+H++is2/fJsHKV+P9UCTs+
            Oww7Ln0Ud4mLN7ffSkhmvXX41Vs38gjzrZDbcNQQEHAMb7TSDsczxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T12:25:09Z"
    mac: ENC[AES256_GCM,data:oMlroWV472BtMmJdzNvtKJ8gqIzoehMNCkTDfKiP5Io689Om5RHJzacMZNaQbuvOZ/r6ODP4j8rwLtzwyf4qgm6Nhekt2TLXOJdacF3ZE8amYoJ/hZuZzvIwp9dY7f/jC1TS1OG2JrWh2Z/cQYaliZanceObhCqhWDyxJRRNvoQ=,iv:HK8Ct0YZySTj7GBR/k8ry/hxhWtNP32NLbxU+CuSJBs=,tag:38nnw0BwkmM/TXUWy4bR0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
