apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6lRm19VxaPMeQ8Hc8E6EaIfCOjGqJjbE,iv:Mkya1YShr1QpvOoxDPXv0Lsq7AFIFhL5HIuIAkyX4Y8=,tag:K2031WWwZI0+HDxLcRiP2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYUhmSnAwWlRVelI0M2RN
            b3M3VERra0pzb0VjU0NDbjcwR05DWmtKbXpJCkRwSEI3dXllalBNK2xGcEtsVWZR
            NS90Tk1ab1ZUK2tQUitvd1hCUTF1alkKLS0tIFMzN3JTSUhJMzlJd2xUZE9vTjUy
            ay93YTMvUFd3U3VIRlJzSFgyMWhuTlkK6C1lQMSURuKcHF/qumo6xS9rsz80gBGk
            kCuIFysIMiN8pRBhsi8usir4SPtvtKVr5/cBD1nDZ4Bjb6iSaVlHVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:05:50Z"
    mac: ENC[AES256_GCM,data:b2wrYsQayYYFCqbys+pyUE6p8Qm5CGMj4Vz/XlR7EW2Z7qhT3HeraqSW8xRHIvWup9WZBzFJeBup9JQUVjXizrdDv3B3mr6Qpww/LkalSWJV97qlzc+icXpCmZFc6ardhyXkHWnG7AYwXh+5ZVFs+AMqnhria/jpkzh9iIkLacc=,iv:d5UtCBWX4qYcZiuWzsZiIn6Xc9zOUGi66nWSvYek54Y=,tag:MygoVqcmwiDl7TyMnfw5HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
