apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OtHsWgu0qvtY3BFxgtn6DBuNZRCFyoZO,iv:Sd7V82HlqZR6dN6ls+dlr6HbNL2Sz77933I3esvOZHQ=,tag:ZuRG4x0UUGZ+odTzmQyupA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWGpUVjR1cS9OWmtOMUY5
            OVB6VmF3aTFFZWl0YURVMm5MVHJMY0hoNlh3CmtFWDdOb1JMWXZjMHQvL1l6SVZZ
            NERVTzlWTXdyK0g5T3gwMEJ0bkNscGcKLS0tIC9lVzdHanI1SFo3V045cHlmMU9w
            Ymw5VkJvUE9BTGMvdGdMSkdJbm9mZlkK6CIj3YDQapvz0szKbUaRIiURKe5K65So
            q/AgrtIQIaL0OVfqoyj54tn+eHt5lLTGMCvV4kNvulBPy2DxfuWT6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T12:14:30Z"
    mac: ENC[AES256_GCM,data:N+Cavurf055VapadV03flJqqY2XxWpzuzuzXkw+1OlcOfB2OFuSmXJnrnlItRh6F6JqAADpR1Eekg98g/Nuau1uMcd9HwuLpkqJM9QMONwHOD3AIgkzGevB15EmkwiT7AiNJfPe/4paOx5JewPLa8TQhtAC1OboxqYONeBD6Zuo=,iv:kI7hfHzbA3+jFTxRAWXZJWjM4/YPHEp+lvZ7IBLsQS4=,tag:S183frYsFQadiJjcE4LR+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
