apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9oAhtaqBukxUZlR5mvEDPL8LOsPcQrUI,iv:MZS0l7kj5dCYdF0khObN9eupLV8DWCOfSnehyE+rWUs=,tag:vrtwbLcd2//nfjsAHf6AlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENXROaFNOTk9odERySlA3
            UmhlcWxSSU9nTW04VUp3Sm8wSDdVaWVZclJ3CjlIMGZPajFKOEtDTkF3YUV0MzF4
            R20vKzBzNExUUEtwRVZkdnVaeDR1UmMKLS0tIGpFd2ZOS2dQZTZvWXRMdHFlOHIx
            RTdJRjBwZzc3ZE1sSnNkeUd6V1dTSTQKdowx4KjDiCkU5YmrgLqZT8+yXibKedkj
            T+pCN0JRMhg9NRWnY/+oF9y51I3JlI0gMQe+XBdRUWJeZlX6CdKJQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T03:16:27Z"
    mac: ENC[AES256_GCM,data:VhDySxWaYBAV0VuDix8L6yt+0GGFnnftUxj4FD4qF9yLvq06kpuq+5azWyoJzxQDn8tgfY6tTGazeHUunhw375AKSnOCltBaZmdkBA/k29hPHomIr46uHaiDN82aIbQoSSEFP9pq7E6Vxj/LX5TLDY58b3ANxnel32ePia10HUI=,iv:9fXQlit1UCgSjoPRtdaXkYgt73kmEsVcfkQySd8d+LM=,tag:Ltkd7FC45XQTTnuS+x9s0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
