apiVersion: v1
kind: Secret
metadata:
    name: cluster-authelia-secrets
    namespace: security
stringData:
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:Uy8ua/M/xJVKPrzlPJQJBhGl5RjjJ5AhzYeZowgPTNE=,iv:H5OZBL6Uir7kkDx3sRQqBGxEdoxEkc4FH6cdv89p4lE=,tag:4demw+flIEBmP5OY8s6aOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTnZGT01CK0RLRk5TTkVi
            blc1c3FhdVhJL1M3RWtzUGpLZ0I5MjlZYWs0CnB1UnJZQ0xhdDF4cmkyU3VQSWxN
            dUZEZ2hJUno2M2lKblJCclg1QThQa00KLS0tIDFVTUJiSEhCdUUwQUMzcTVLTFFK
            c1c4bUtTdWMvS1RicElMckNTK3EvUm8KYfQKu2/7WKjkOcd1bq/U8xdjWO6QbUhz
            LpZnk24yKRZSF2OBAnDfhLI/emyyCnyf+xdMkf9C+kNXJjTEKld/KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:07:08Z"
    mac: ENC[AES256_GCM,data:zESAckw/+SQCuy3UpwBbs7yW/qWve6YdDz8EhV8x2k0SrNLfnUx1+3lbqPcXD7Exy+TQazy9CIqFL3pyGoG1vdg0+60y/wuZa0fAa6DTKn1ZssNHwywQpBa43tXyxFFch/rdPamSrspQbkk1H8/gWo8bRFj9PhlmlnOezD2X8XQ=,iv:n6gsIJKOFnLF1rwP6iwo2NixwFBEOLs6NqLZmmYHUxc=,tag:MCaCeGku5rtcKBV92SEwiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
