---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/authentik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-cloudnative-pg
  #   - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-longhorn

  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m