---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  # dependsOn:
  # - name: vpn-gateway
  #   namespace: vpn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
      pullPolicy: Always

    hostname: qb

    podAnnotations:
      setGateway: "true"

    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: OnRootMismatch

    # settings:
    #   automaticPortSetup: true

    env:
      TZ: "${TIMEZONE}"
      UMASK: "022"

    persistence:
      config:
        enabled: true
        existingClaim: pvc-qb-config
      media:
        enabled: false
        # type: custom
        # volumeSpec:
        #   nfs:
        #     server: ${SECRET_NAS1}
        #     path: /mnt/fatguys/Media
        # mountPath: /media

    podSecurityContext:
      supplementalGroups:
      - 65539

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          # kubernetes.io/ingress.class: "nginx-internal"
        hosts:
        - host: &host qb.${SECRET_DOMAIN}
          paths:
          - path: /
        tls:
        - hosts:
          - *host

    resources:
      requests:
        cpu: "0.3"
        memory: "1000Mi"
      limits:
        memory: "4000Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qb-config
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Mi       