---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultSettings:
      # backupTarget: "nfs://${NAS0_IP}:/volume1/longhorn-backups"
      defaultReplicaCount: 3
    longhornUI:
      replicas: 3
    ingress:
      enabled: true
      ingressClassName: "external"
      host: longhorn.${SECRET_DOMAIN}
      path: /
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
