---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: external
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls:
        - hosts:
            - *host
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"