apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:fHkpJNNU1R15Wa1ewizryzGb3cTwPRrS5xd1wqs9l/nkRfE6Jf00qQ==,iv:05V3KJvvDjHoidskPmBnMHIAzWy0hOW5zvxWY5LXNMk=,tag:sWaDCO1mrBt+eIEW/MhK3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UFJOVk9qbWt3T1FodWRp
            V094R3hUZGFrRGZBMEkyMlN6U2laL0tHWFFnCkk5Q0NZOWowaE9KbjB6ZGhIUFp1
            MHNMbGRQbW5KbWRveTBwOFk0U29CLzgKLS0tIHAwRG53Q2xHMUtTUkJJWjQ0cTlP
            a2JHeEc2Z25WckRKNjBrbFptT0RlMk0KKJLnynJxri2bK62W7Yz4VefCMKAgf1cU
            bgkjXmAho2KWFPtx14QP63ymx+8lTqf1tKF/evLqduqPT0O7zMPVPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T09:22:09Z"
    mac: ENC[AES256_GCM,data:LVd9LH5bzeG/D81OInwKCjSw4tQi04324KuM450l1pwtmbuIz+U0IK8vzNVqw3jtnhOGFVrYBSmC/KEiFBmFRidf8StkZHMJP45wbH8C8U1Zh0TqVDOxZhV4ymVB0TGr2CrmPMePICm374ZdxrbdgZQJ8xYo5LTuGGcDpC4ZtD0=,iv:vnfLsrsLtCGBuPP/DASJhBj/Et3RzMSL9NdeDYDv54U=,tag:aC7CEe2Yp2HMdsovu/Eq3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
