apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ri0wJh3RsJsqupSGim09VdJhbxoST6IEIaFW0T42lyDUUXN9Lhl3ZA==,iv:M36VkDJ5x1x5tNkQ+kZAo5le0JP2JAeDXfUqu7J74gY=,tag:rTrOCRn7ROESN4LbVKrTXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WlpSMlVsUVFPb0NoZnB2
            eUl2TG5tU3RpdE41YTBFWWptOG1kL0RUZ0R3CndPWmZpaHJrTmtPMUk0WW5aUXJM
            NW9PeFNVQnVwVTdDdjI4WVBwMDFkK1UKLS0tIFArMTVCRHdpcFZMWUp5UE9mKy9M
            SGdyU21KL1M4UU9ndzFlbFBVVGRyUzAK460s0RQojTYUSIoQId9tPCCW1Jbtmkag
            77iA/Cn2fKypve3nikWgA6nwqLvo8GPLM78ZNNRGkfiChM0Wlkl/Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:07:12Z"
    mac: ENC[AES256_GCM,data:mcn5C264Fc5hzBjRokhHkuJsYA9fmnUuiGGjEA8A/ITYatZRMsegu//PVBRfWkUW2XlIUmsOvrTsjkfPXASADb8vqihOUkdjYcY3KtzZ6gMZdCZmrZvuQWlEcq6U6qzWHbhLXhePAO2IJKxbBCjS9PqcHOFIJiGcttynP1dbRdo=,iv:mKzmmJ3TVYvX7BcN4Q9Lx+Ku+EeRL8DD4a1Pv2UMJpg=,tag:5HEtgyEVxnPwj/sUH8Urgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
