apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:YzJ/a8vjdyATTuydNWzWRaZXap/jl5mwDyHfXhpqyPIedukdVWE8lQ==,iv:f+LLjegq3jr6hiDh8xvgjRbVu9prOiuLIuybpwekca0=,tag:e+9Pwsl7rYfJHjQs4sZtCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WVd3TnRWZ3YyMmwvS2lO
            dWQ2amw3dDlXWWFTUTFjeDJ3Y1ZpaGEvYWtFClpCWGdrdWw5R0toZ015QnRmYzhR
            Zmxoa1BPaVhJakJ3RzhkblYzSXh0ekEKLS0tIGJvWkZRQjhOMkM3OGp1a3V2ZEVp
            OFQ2a2MzWkp2WTRrWjgyaHMrU3ZwN1kKv8Rh0JGFZF3G+XgdhC7KF3Dm5nF/ac0q
            3ji5a+CJpgZy76uZqUcpbLYlnrAo8VkJMm+4TtxTl0EWNxLs3iqQbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T14:52:59Z"
    mac: ENC[AES256_GCM,data:Q5aXE3/Q3cOpFmIbq5NExWJ1Ad+BXxzH+mvjphj7poZkQ7iAylqv7be7kX73kS2MepXDzOn/HVqtQxU5ZblOVql3uDivEY5WAmmY170MUE7mfXcuvUk0pnBdu177snpkE0DLSXn+DYXFmVB2x+RDeyGaY2ooyPe1yJvsyaAoxFs=,iv:R0lSJHK0Z3MtHMJsOTyr/AU7razTSSH8FxszIGRqbC8=,tag:os1/dDCpJ60GDvqmkFyZ2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
