apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:qvESmRUqkpkObyLirQoukazxTq2iUPQHERuTzyb/6k+wUYfb2eTWTA==,iv:FbAPG/D46Y5rVNjRtf0ofFl56KQgUXGz5aQ5oA19eYw=,tag:9z2/EvkSLnwPyzn0Kioedg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ25uVGtTRExteUdRN2ww
            WDkyMk5kbDRWR1E3Qjg0UCs2WGNMUmhZUmxBCjJQS3ZXUG5kaVBvY0NYalZCM2ht
            dTJOQ1ZmcUljdXM3VUo0QlNLL1ZMK0EKLS0tIDk5cUQ2TThHUDM5U1JJSTMvVjhK
            NW82dkJGR2RJcXVxRnpWcTRXcVRoWm8K/ypEEpEET6rDo3CS+FolDxDHTtR9MPjp
            JbF5dZtNMXhjY49KPxP/x24g4Msd/vOwlLpQc979rvWap93RsnPIng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T06:03:06Z"
    mac: ENC[AES256_GCM,data:RR9ZXvhpxTxxJQhnndDax7Vcy9sYji4oO3q7XNnSpaOv52P2hcLRmZCWU8PtZ/WAFkq39JoFHfGoYlDZLBQgLsvCwrs1tIyAcSMB24ElkhMzE+k+R0l6dZ33sBMTenHHlFWRPlqQx7fcswuldnuMlYv7USeZ5E7vBFvd8bwAPJE=,iv:ynTVGQGhsoivNlrYv8Bb2aFs7/XnnzTuaKys8+mAqw0=,tag:WdjzDlMz9yBktzJuzCi6mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
