apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:bnMT9/BXp30nXQLEhiD+f7EkpexLie4gneyBjESLSwOktKP3pDnyOw==,iv:3TiLwwyUyNQyN0uth4cc7t2SoTi/MnoVdzjsk8RXqtg=,tag:CYxcRw36LzDoxuMZb91sNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYm5PcFdxbTh2Nk12eXY0
            NnBMRTNyeFZOZkJ3ODUxZHo1UnVjQUdRVVEwCnZqZXJPNkRZK1hFYldOMk5GS1VO
            Y0dmTU42U01jWm95aGRjdWlmamFFYWcKLS0tIHAxbFlPNTg4VFdnL0FsbXVZRnha
            MHB6SVQxY2d5dlVkZlJyK2E5SWRDdVkK8iRizoju1f8WNejCj4NVfmFjSrnC6DWR
            wz9yHryqe5c9yz25z9Kt10xlLL+q8y+C6TkprlB6IZu8hJHWpOtjzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:20:06Z"
    mac: ENC[AES256_GCM,data:4VKnK2OSeqOaDRHj37SqhSKF6LhZ6ph90NsX+soIgWfZnXzgdMNp2gVxqM7UyPBwg/rmOAVcTbgLEXHVHaJLC9SXjHCln322XlV+hSDtmYC8l/d8Cgfyi2/wBlIw90s9eGKYpIAR0HhMJFd81rC8w7Vf3pCmElenTWJPT2Gxmgg=,iv:ekFT8vCpJGeEq8XRkbZuJQuPJ+9LfshjHVGsfI7Emy8=,tag:qPQWzwjnOm5cTMkLYYCMbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
