apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:PJE09ZdNtGI0RGZ90xljpvBMQUd0DX7/QAGM/iqnZeoo3lLx7Hu47w==,iv:qPcYhE1okCPsG2XqyV82ZljPbAPXVlv7psyphAtKyFA=,tag:UenZyAkx7fchAVXbFjmolg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNUk5WmJ3VFByWmpTV2pI
            NStGVy9BWjZzdHpKTjFNVXBqTk9kY1hwVVhvCmc3UUFReGVnV24xOVZpelVUbGlh
            RHc4WmpJWUZwVk5ZYkQxb29RQjlzcU0KLS0tIG4vYWVnK2JYc0hhWlpYQTJaUlpO
            dnJueW04OUhKUUZxZ09la0lwd1VUT2sK18PaZQ2PQtKO/N94kjxxqRG1VbwvNCzD
            HEkIKJCIlv1yjFBAe+5j8qQ8Uz+yc1NcOVs8gehb3qYsppQxh/8rGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T14:17:29Z"
    mac: ENC[AES256_GCM,data:xmsooTO2bpMaeOZrbczXEvh6dhPQmdtIr6YNtR2rN/SeCwkuE6mEsX6wmrZs+jkZM4WX2Q/ZzPiqOrhTec/E7o1/tqd7jRyOuNApTko47h3HKwOAKgP4acjzRkcukb58CV/jjmd3UGWOWAMnbUXmWmSJ0HCRaZE3zw50P0wB1dQ=,iv:xiX3mi0TiH4V3Ul6mNoA6nys0Q2HubS3TDYmD8BqJY8=,tag:c+dts1QZ1eJ5vPWOBkkKAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
