apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:MVw4vtJH9tk61qILc5cE+st0mWZ0lAvbjrNFOFrMA7bIxSF34HSVwA==,iv:nQiWt01RwcwurQzLV7c0ekmUPjvm8EY1rfBAqJXH8ks=,tag:ssXgYfMIF/NKSwLwh0jsKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU0x1T2wzNGpsWVpmaWVE
            TCtab1k0TmlVbHVCQ0kvTzJ2V2FMWXArVFZjCmhEcXcxSlJCb3lYNnV3ajlyUkZ2
            TEJaVExUQTgyZDVpdnVDbzdvMnpDY3MKLS0tIFZlTTBSd3FBc1BvUG5qcVZRdXg1
            cytpUFVPaTJBWXVRTkErY3J6SXJBWFEKSWkqYuymyXo1jXoi2RC/FswV41kIDaDm
            QNZihujzbilUljvj9RCsBuk4QaWy5RUQwnRwYVOfP9+4eZJ7anskJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T14:43:53Z"
    mac: ENC[AES256_GCM,data:jpiSfwV7N+Z78df0XOQsIWVyRXntItt/zaqrgZf8CtXvxyF7Desgp0S61SGQW6QF03Orqs6Hu31t/zBLGmYX7t8n8b5XCESUiHD+c5pNgFyEA6oExi10ByWmNWCSN7TFE+QM8Yf7wmR9qkKTOCtNlhGZ/e5wk80gZbsil//pG6s=,iv:S0YLO96qvxtZSJU4t7nZl0a3vJOFjIhYnkyOHt/G2Tk=,tag:sw9NfoaBFwixtzKii30XXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
