apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:vScDYmUG7qPPhVAQUF3MyBUAnpFDmHT0X03NRaCj2w/5GCJb8CZh6g==,iv:j+KPC4s94MUvlkgjtM+7EumC1eG6IVmCEelLkjBsjOs=,tag:wSvJQ5lGuNJ28/F1KXOGzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcEJJMlVJd0N0MjJkK25J
            NlBHUnJzRmxVRWx3UklPUEZwUW0zS3Q2NmtJCklQYjZVZ0ZrZEpaQXUvN3VYTEs4
            S0I4ZkxjaUhvZng2L3lCVC9WejVxSWcKLS0tIDFPS3BjK1VZTG9LdS9uSVRaLzF4
            M1F0RVRNTjh4VjBXZUUwbitZM2xIRFEKNv8oyT7UkEPoeJlLqMbu+Iw47sKncrdb
            /5hwcptZ3gUR0jsuJpYk3NH/9v5epApGqlmRfRG/e+oDcLtbbjXQ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T11:34:38Z"
    mac: ENC[AES256_GCM,data:+6YbM7TalZP7XZz547I7me8D+c9e2XhGGFjh0Vf1RLh2BBkRyKNF3mlXbg+LQ24C5ehegcT1Vy48xdTjC/jDjE8OwHQ5nPuSZxXfRMuIM4CUIRFBQ1FMAy73Mcde6gDGcdZYm+2rUo9Nt1+dxA10ekc/liJewGKKwpYzwwcFmOY=,iv:zUOGKANB5T290NR79yVpWUrg4Cbl+QtQe+oe/1GrHGg=,tag:BFkgLFHGB7WDpYlUMZyi0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
