apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Wc9Lzlqd68MF2FqgZFSsmGxjn4uHP5yaEL4fNJYUq8H52lnCYdndcA==,iv:McA5lpLgjqEIg67LLbSBS/ZN8m0Z/g6kwg+yoHCxVZQ=,tag:Lc2JUOqUXOSCfOjusv/q/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ulc0L2hzRDViOGNDdjFT
            NzdVRXNZNnVBV1N3NU9JY2E5b3h5Q3dVQnpVCmlTY25jYy94a1pPMTFOVm5zZTJt
            OWM5SVRSRUptM1pNNEpBNjZMdGwxcUUKLS0tIGhXRDRERy9nb0FsejlGUzdScUpr
            Q0NPZTN1WVB3TGVjcUlwK3N0Qmh6UHcKpmYn5LuMk0C4slxmhlRvr93xtPlzPMjg
            8uIilJWIm9SFr/oplpvxcQoMkrxdBpyzEj9rG2yRc5MvNHcK5550VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T02:51:02Z"
    mac: ENC[AES256_GCM,data:RiK13HIibWE2dF3REXDBjOC+Rh+9PCUXmSXtGs6dK5QQcYOdk9ttZ6aG4KK8lngFIl6elm9+NN7pj3kZlzQzZ3jLsiQnCEGZESoqZEuFipKpBy4Jd2verAsaDF2cSMeq366JvlrMPhhqFtqHrDQNEOnNnxc5rkGQlgk/OAiGG1o=,iv:if9e5ETfBQjZW6G/4LTgR7P/9c4h8dm5eXrY5soTP1I=,tag:I8YSlPPM6OXqDVztZw/uxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
