apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:SUNKZ7mivHEzyoAYGNta+V+rFqfUJA5HPInEKEI2XzbJUYuRhJGdZA==,iv:+ePF/cunt0Z344GczxESYmb7A64aMjspIJ20YlFPmVM=,tag:v7CFKLw64z7+zPn4oQKKxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbExxRlNVVzg3Kzh1dmlJ
            L2JOSFRWZVJ4VnBhSDcwbm5nRU5ObG84WldjClY3amhKdEdsd1h2Y3o2dFU5b20r
            Qm5JdWhubmorbDNsenJhNkNkZjZENjQKLS0tIEcrL2JhN3lEZUZmL1hXejJqQzFl
            eVAvS2NMZ0hYK1ZraWpDR0JZTGNYUWMKK+kvwUNKj6PY261F6JAhfBEHnABY3KtX
            lzu86IoehxwnfmuI54JTB5upt9okTC902qUlP25bGXHWfo/CU3y8Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T06:03:05Z"
    mac: ENC[AES256_GCM,data:bysSv7beN6YTcNAJwpgxJbcWQzbLt5bygsKWMU6KFenRVF4W/ENcJyvt3cwGYpBx641TYZxlOdUTdX1jE/7eR6VUQYUx+qS3Y5jUpPN45fuMqypO4tCi2GDyO9SiHEop7t4Mvix2dmRAKnDUs3gYcc7H6WYiFGrHzOBWwi2aI8g=,iv:BEq2W2dTgx46+Uy4jJYV4yo8OQLUuHuayWzhMJpSfow=,tag:YZs9RZGAQax/yU66RR8Ryw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
