---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "${TIMEZONE}"
      PUID: "8675309"
      PGID: "8675309"

    ingress:
      enabled: true
      ingressClassName: "internal"
      hosts:
        - host: &host "jackett.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      config:
        enabled: true
        storageClass: "nfs-kube"
        accessMode: ReadWriteOnce
        # size: "1Gi"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi