---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "${TIMEZONE}"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          # kubernetes.io/ingress.class: "nginx-internal"
        hosts:
        - host: &host radarr.${SECRET_DOMAIN}
          paths:
          - path: /
        tls:
        - hosts:
          - *host
    persistence:
      config:
        enabled: true
        storageClass: "nfs-kube"
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: "/mnt/media"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: media
  name: nfs-media-pv
spec:
  storageClassName: media
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # mountOptions:
  #   - hard
  #   - nfsvers=3
  claimRef:
    namespace: media
    name: nfs-media-pvc
  nfs:
    path: /mnt/lab-pool/k3s-nfs/Movies
    server: 10.32.1.5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nfs-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: media
  volumeName: nfs-media-pv