# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.1.2.8207@sha256:7e026aae3fa4ac9d4066a0533fdbfaa35a0ccdc41033bc4f2460aa9401ecfb46

    env:
      TZ: ${TIMEZONE}
      # RADARR__AUTHENTICATION_METHOD: External
      # RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
      # RADARR__INSTANCE_NAME: Radarr
      # RADARR__PORT: &port 7878
      # RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
      # RADARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: &port 7878

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host


    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn

    persistence:
      media:
        enabled: true
        type: nfs
        server: 10.32.1.5
        path: /mnt/lab-pool/k3s-nfs/Media
        mountPath: /media

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 1408M