---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "${TIMEZONE}"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      main:
        enabled: true
        ingressClassName: internal 
        hosts:
        - host: &host radarr.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce  
        size: "1Gi"
      media:
        enabled: true
        existingClaim: jackett-media
        mountPath: "/mnt/media"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi  