---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "${TIMEZONE}"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      ingressClassName: "internal"
      annotations:
        # kubernetes.io/ingress.class: "nginx-internal"
      hosts:
      - host: &host radarr.${SECRET_DOMAIN}
        paths:
        - path: /
      tls:
      - hosts:
        - *host
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      media:
        enabled: true
        mountPath: /movies
        existingClaim: movies
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: "/mnt/lab-pool/k3s-nfs/Movies"
    server: "10.32.1.5"
  storageClassName: movies
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: movies
  volumeMode: Filesystem