---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: radarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  # dependsOn:
  #   - name: nfs-subdir-external-provisioner
  #     namespace: storage
  #   - name: cert-manager
  #     namespace: networking
  #   - name: ingress-nginx
  #     namespace: networking
  values:
    image:
      repository: linuxserver/radarr
      tag: nightly-version-5.1.3.8226
    env:
      TZ: "${TIMEZONE}"
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: 'true'
          hajimari.io/icon: movie-search
          hajimari.io/group: Internal
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
           
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      media:
        enabled: true
        type: nfs
        server: "${SECRET_BACKUP_SERVER}"
        path: /mnt/lab-pool/k3s-nfs/Movies
        globalMounts:
          - path: /movies   
      downloads:
        enabled: true
        type: nfs
        server: "${SECRET_BACKUP_SERVER}"
        path: /mnt/lab-pool/k3s-nfs/Media
        globalMounts:
          - path: /downloads   