apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: radarr-config
    namespace: media
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Rf1z13Vg1XVi9RnHiUjfEhkzHupTNWhIsigmhHxd,iv:SLCMjbqPXstQIcR4HXLHzR2KF6GkKiy/U+kmcxFDo/8=,tag:TrZNSIref3CsE6QmhAkN+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dXFGUmppM1BtWGd2TjNR
            TkZqa1E5S1VoZnRKN0x3SnFlL1ZidHBpMTJZCmFwZmhhOE5nalBqdU1BNXNOUG40
            eDFRR0laWm9EUzVuc3ZJeUN4b1ZOWXMKLS0tIHc0UXpVL0RHcUxFSHhBdldRY1NQ
            QmRnZ1hMUE1GRVdCSGovVHdkUzkxdjAKEXsRywOO4D6jJCit/FTRgLP0Tp+sYLJr
            SNN2D4Ox6ZZviVu1HBYw/FqAN2DdfsgrUKFMT5d8i3Ag8t1hkGkblg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T02:53:16Z"
    mac: ENC[AES256_GCM,data:BSYDPDRjxUNKuxHmxddlaccgpW39KqyAsrgldZniV98WpxVRcWdtf7s9wmyL3mIjLu+kLfMLc1Btgw9Zu5AdxY+Ld+wf5eJRLRnuA108mPS4F2iKW0FAeHkEUIc11kpuYN8Zwy4TqvcHkaVnEPfRAdjWeb9rKjRP3icbpdG+j8U=,iv:wIUxn1gQtZdHq5uM9RBOXkr00y+1oAYfXXuu2dR+OOQ=,tag:REfiEoWUGh6wQRQnN84ElQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
