apiVersion: v1
kind: Secret
metadata:
    name: ghost-secrets
    namespace: media
stringData:
    rootUser: ENC[AES256_GCM,data:4x84h0Dw,iv:/OcDB6hLmwvtOQLkidq//CxSIsMn6IhB9WIqR++WrQY=,tag:Q5USvLfMO+kLXnswb1B/+Q==,type:str]
    rootHost: ENC[AES256_GCM,data:gextgDg=,iv:4/Sp09tVgj+Jq8M3SkuXgIh7JmL3z7U95fRzOWDpXeI=,tag:iwsrbedPSvkgz97kglQd5w==,type:str]
    rootPassword: ENC[AES256_GCM,data:nVY1UkEkBjOQFutyoBdi8ZOJ9Q==,iv:w09fxJelmnnfaQ/E3jcc9snXy6SfrD+gaaA353paAYk=,tag:ZspVViCr6fbCaZcgQt+FxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dXFGUmppM1BtWGd2TjNR
            TkZqa1E5S1VoZnRKN0x3SnFlL1ZidHBpMTJZCmFwZmhhOE5nalBqdU1BNXNOUG40
            eDFRR0laWm9EUzVuc3ZJeUN4b1ZOWXMKLS0tIHc0UXpVL0RHcUxFSHhBdldRY1NQ
            QmRnZ1hMUE1GRVdCSGovVHdkUzkxdjAKEXsRywOO4D6jJCit/FTRgLP0Tp+sYLJr
            SNN2D4Ox6ZZviVu1HBYw/FqAN2DdfsgrUKFMT5d8i3Ag8t1hkGkblg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T13:25:19Z"
    mac: ENC[AES256_GCM,data:NyhsqftiTjY6njqeMFZXuyQuBnScZeB85Q3k+b+Y72JqRDGDAPFDNrbDSl+RC23AHxDMjzlafcyXSmPapE5E44ycfPJWoZa+MiZMcprKctAKQEqHXJgMpdzMjCGIRt/EJt2PYAjv3BlfGLsvJp1KRFGfruJuWFYk72DbKf5B5Dc=,iv:oPjncAQMJRHo9NSuThrSmRYy0DgNmrmFW6xvE/kfGPc=,tag:qg88CW5qLItFOhgVjmwfxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
