---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dbms
resources:
  - ./cluster.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  - ./service.yaml

