apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage-system
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:CtbALRVYZ6DRTF9bZj3MapcFB+aeic0TwDzkStc1TkU=,iv:llCzPWdlKwCNJfKcEh84kRHJpfpAzSlRKmMg3XaRHIA=,tag:FehRCB4X3FAaeGi9mf+kfw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:4vd1l0XrNYXWzlE1HyCpzQ==,iv:2OWn9Oqg82lOjAMExTDkgP14upFTkag4NVAzQ4zI3TA=,tag:0VUne3dqCGHwcQQocPsiRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dzdSdERzaGIzYnRlOVNh
            THBGM3VxK3J4aDhuWW55WnJJZHdsMWVkNldRCmxvMzlpR3hHbGtlVHJRNm4yZ3ht
            dC95Y1hFRHd5YXpLem85RHNDSnlKZ28KLS0tIFU1ZHN1NEJhOUlOUWdlRTRJUnh1
            Q1l5NUVmYmRqUHlvL2taNGx6U01YUm8KlnoHBZgwLZ2+O1F9x3oFzTOWA3rS1TJp
            VCIoTlJvyOXp7oGKyrixdS8LDRdvgYV1xY9ISG35zRQdIMxYqtAd8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T02:51:18Z"
    mac: ENC[AES256_GCM,data:mscczNUnONnsUAoflgMhaT6zsKkAU7czNrOEie+ULZW0xg2V+MVOTvzUHoCujLfOtexsyAkPp4BnwWjosoP5Oq2DHegWvHst+HqV/R0HUlJKOiHvf1ORm7kc/mW8pAtBo52UYE5/0A9q82HOcL+vLJnH7w6v+WrkqxCZF7VDR3I=,iv:5UFAgSexXADJvDJzaKEUDxVPDoZZz1Ebmxac5FuY7h8=,tag:fqelBCbf71qgrmr6WLcJgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
