apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage-system
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:q0+BQ/LHGFmOORvPQq+dJHYeJi2uNo3mseoLSxl1va4=,iv:b5osuXXG8PcnVIVcVNJajSpCC/MC6b5Epw7COESsUo0=,tag:Bf4CqJSaIu0vxddrg8l1AQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:znLn5KWHsyhh7YI8xqdb5Q==,iv:HYiiM/nz6D/OfCbJtl9GP+Lg2p3Zl1C5NLyAbxvzmBw=,tag:HmeAJGSE8WUu0Fqj178uAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcHFmWXRWbU5tTDFnSERi
            ck1rRk5ReWVpZFA2a3FLaS9rSndJMTBQM0JnCnB1b3RmWnhCSnppMXNVaVhLeG1y
            UnlhL1NCSnErL1V5dVZDU2djY1VlMjgKLS0tIGNFazV4d1JHaVdZUmNIaHZXcHlQ
            a1RwZGtqaVlGbk1tVXpxNUwvandETG8KibiTXPgthxbSS9S591anOdVB4BZQhfyi
            wpICTid25RCXSqbgZDXpCKfuKieJQ6qeUjmXye+0oWJ0rjtqYpIPLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:07:13Z"
    mac: ENC[AES256_GCM,data:D9503CJ6LuWqcjMqi81xdHwvGlo/5y02+1RdDSuEemurtiMznTPw61MW8HNIbXATiQDBNsV+/GF7Lh5JPyvk/27nR6vIrOEj/hia5kvfv3ihjsTGCN49Ipf+RKP/znoYe7xm3teOGnmgQvt1Z52gHbjwyypof/iY2JicqLVQJbQ=,iv:zho3FHiqr7O4PYkYtO0z1/bUNrNFbEjUg3g/KHOUPb8=,tag:5F23IyVBVuE54CD9Ly5UDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
