apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage-system
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:u7evIARIbYZXKzyiou0er+7Qb4Ok0grixI4ehL/rXuo=,iv:IN0x2vfGXzxaL8RnPvymGeMmELKz9QJKt1i31y/hlrE=,tag:awreelhSZpEG8jej9SLjTQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:my/RhVuEDhPPtIC/SvBVyw==,iv:7l5nbhdbDtp6J71WowBrWbQLlgiOstBK6ATlDHyn508=,tag:fGuneB0lFtQXJm5lEGTWqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjdycnJTaVA0MHJibFZm
            VmUxZzRaaFh3Y2lOT29yNEJTRWlhRElwMXc0CjVRMjNhTzFsMWZSb3g4LzFpUUJ5
            N1FadldQTFVBZTY4eWp0TFNKQTVDTm8KLS0tIGVxNUZROXM0WWZTS1BQQnBMdkxU
            dTk1d1RVU3JqRlROZmlpS2VXY0p4STgKpl+s5Re8c6xw1joEqzG+HmPL4TrX1RnU
            Dnz219EdPPKc0QNFE66sChvCC6i9FGVB6uuLwpwJLS2Ud3jmXS+gIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:53:54Z"
    mac: ENC[AES256_GCM,data:49ppIREBjlVP3ocCVPQR0bhMPN+Nhu8pPnmlrUqKqVBnI2j1//dUoFPfBoMuTdeXqteyEMC+B7Bn3suNnnz2g/2PoHiEFLcxl2+vJvxR6RPghVC/2lc2QtPPkutGsbpVlEMKVkWP2rYD50mrb7OCBQIn+uGRk7bYlQ6ES/Xe8SU=,iv:xxlkj2PKG1aa/gCaezOiH4GYI+ZbUZWFgiiWOIz7sf0=,tag:4x29T5aRYekcuZ+JJkCLRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
