apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage-system
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:fDynS8wvtG7Cl4ttxAH7dlcmB5TaQcx/UAS+D61oBg4=,iv:odZmyVFI/d9PsdN/3niQ119zGmI8HjxgMa+QV3FoNHQ=,tag:FKLv6/VI2qPXPttiw9K6RQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:ZG7if7x31+9ISrV6wTDZug==,iv:hj7W/B6fkHv/uy+F/mhqo0YaRpIbqJqmUjiYct/XUGc=,tag:2uvHye2eKNFh7pIrX9AlhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNzFRZFFIa3k1aUhyMjBa
            ZGZ2SG1DdS9Pd213di84VTJIOWlGb1dPUUVZCjE0a2NnNUpyM0ZCN3Z4ZHB6Rm80
            RWhOa0VyS2FNMmVuZGhLemZQTGRGeUkKLS0tIHAxRTV5dHF4RFNNaUt5ZGo2SVpm
            cTJJNGhEaElDM2JuMys1OTRPazdBZDAKqamPqhKzR0azXyO/sekwbDfrJCkfiJnX
            R+/vNz782q6oVr0ZZkymSmULnRsrFaZgZGVF/G++nH56y9VNKfv4yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T12:25:21Z"
    mac: ENC[AES256_GCM,data:/sGpLSJecg/a70pIXnK5cOcjvhTg8toNjZxxpuYsTlEXEoa77nUhj1dT8nhKKFCkLVc5q4gGOkOi/1uYyA9HLTPZdd8L8869w7deUOFCaHO85h4HiJagpc67EKm57czdUwqIrJRHW4SkX+5aqk8qu2tnrL/2+qoXKfetOLwv/1U=,iv:LN62T3S5Sayy0gr0B3dK6o8d4NdFpT03VhUDC2moU7k=,tag:C4dVvasAM3JG6H0PRP6wJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
