apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:RUmB9WfsVhFnq6tKHuK1cDYI6UvEI0Vmh4EKQqm3DXrxxC6he3hd2zSyVdQQ0bR7L1p5Fe18djTEiBsF,iv:IaWm2BOpknA+hDlhjB5Op67nMnfrQr9nYMUh4YHp7zA=,tag:s3XU1kbmA/um1KE6iCbVSg==,type:str]
    username: ENC[AES256_GCM,data:uE7YjCI=,iv:0BKwIdM/SLDqkkMRG0oqXvEOnptIJ2U9KKh/iJ2fn80=,tag:SMX6ZHSrs4khL0VdTkiHLw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTmNsUDU2ekV0T1dHZjAz
            d0ZuWDYwWEk0VjhtakJqUVAwdzUyMVRONUh3Cm9ER0E0d0lVY1hyS3Y3dE5peDZV
            U0xzbkVpTWpWL29MWUVmZTNiUGF6S2sKLS0tIHZBaG05enowU3c1b2tqNU1oWXds
            QVhTbENKcjNncEp1cXRDU1F3UU9jRjAKsbCMlRqcUGuUo8NOmHndBQi1gb3pKk1P
            CSWRWrBGY6pcRbBBV8VZjIhruCtTtPAVRQFbah4NDcKXTNx/R8Ocow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T13:45:47Z"
    mac: ENC[AES256_GCM,data:7FhlbEpY+/0kKZ+GoH+RFLHZcyTrgwpsYJl/hmm7HajMNuLggpkwKF9FUX3uYo8SBk4M0K9D4t8lczPZjH29882Ndg9NHzg+BzM43afIJNI4FMMhv9fNHw5wzhY9iCVZHBFg+QGqvMPgbJ0hL4Z1etV0IJP8yMfsyKiQfeupS3w=,iv:2rfGkd8kIJCESNCVrY76zqIapB6KKgnamd1emRj1dB0=,tag:3gH9NVwPuKb0cYRZtPUN9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
