apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:Ab6AocEIe0sQSB4SIVXvCQkewHNdcuXt/0fXbRS3iOPFthhV4O6n33AHh2bIzW/pNtPrXdLTzR3Ddnp5,iv:HMa6r8Dkdc1N1yMcQ/DwqXNEVQYJRXBBaTNoNlghyvU=,tag:ZLgfvtv5PNOuGFZ7+6Uctg==,type:str]
    username: ENC[AES256_GCM,data:/O3XFY0=,iv:pSsFXsixMixl+VPR9KB2ePeZV9mpmZERszMvXWfYFC0=,tag:KV/hwsltV0/ee3V4/4aFIQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOelVFV2JBSW9RWDVMWnBZ
            QkhZa2txbVZqam5rSU00Tm4zRWhJSnA3bldnCjcrMWZsME82UXdwRlUvdmE3b2NY
            VkoyK3ozRmYxT2p6Y0tzSkFKZDR1bU0KLS0tIEJsL1pScXNJVlAwWGFyeHlhbkti
            c0c5aVVFS3NuQnhLejRjV3VjUTJhQ3MK4JqIEkGmD14VrFxc/Gblt0sp+jethfMm
            RzNP6Kp9lWFVyWb+UC853a1zVeqR3rbwEQtsjJG0UvH5gvVMxXpRog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:12:12Z"
    mac: ENC[AES256_GCM,data:h2lF7m1b/X1SYRCmqhWSjDh1HXDBsFbz2rA6fgkfTI7x33ljCNmY62gb0YJG8x9sckisZuhWHaN5H7n7eoYsQgD5+Q5JYgiqONE7Opz3wsIlZ+24fIJe/MbNXZLxD9aakmOBaC5Npc2tQOxgZZC9Jc2B8WCg6NRY/VZSrg36KQ8=,iv:RvLUwnSaRPn0vyMoK46uBYhMaQLFfdgTEMT3v0LAt/8=,tag:bRLAvrsvM3iMBQe4pUsjgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
