apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:PSHHgRED6yA2pbYcRK4huqLQlXu0qoVwBWoE7Y1gnUYUj/utkWydI1sIJOr9id0Nuu6paKzN3HZ+tgcL,iv:Q/DlST0OjBTT2jSWoquhe8V+iLA1amHrwtkPJ7tkwVw=,tag:Tg8DulBbT7spY+CNfIy0JA==,type:str]
    username: ENC[AES256_GCM,data:Iyuv48s=,iv:2i2amU6cc5Eptx/O41zGwxVvERUSDlC1QeHDDihaGSI=,tag:3BjOEAUYpR+Pqi1ETIz+Yg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ2pXR2x1bVBtQnB6cUE3
            NkVoekNNanpTR3ZLTE5tbkJDN0ppaTFBK0FJCmFwUHc5a094M3FlRkdhRXVucHZ1
            dWVNcUZkN2U1N0pFM2Z3Y2NFMGRHOGcKLS0tIENZUUllWVBZaTM4Z3QzVW9TVURh
            Z0lSNGJOclpWVi94Z2hKTDNtbTBQOHMKvM6/HIQFJvJAfdRm0gQx3aNTP/e4L742
            HWMkNbPnttNA4luX/ddLgSpm0H5SaqCbSP0seduWgQVJk0YHgrPdAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T06:03:54Z"
    mac: ENC[AES256_GCM,data:TOVZrYbgJsumbmmEkxVA41h4uWQEtzVJY/RinXf7uoVgGQL+iaN9rEeXKuHp4N1jMj0wGSShWEN3YJyZMF01KPM02/LoEz3R/0ZxCumAkoIRxfqS16lP0u6cwV47f03IUoJh8987B+tHcLJcWzl3v4itOEhStCkr3WNE1dZwzQU=,iv:ZySm7a3EHnLuUx78rdyiZoWaCEBawAS1Ksa7y/C2Kmk=,tag:GsZhcYLnK8oYFSU5CYmSkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
