apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:YeZOfTIWIz825u61nnDw8uyf3l6g3sUNnD4T/rgmy7pjarEqdo4iM5CxgC/3jKFYvePdn76wVkw+9uSg,iv:f7lXJDwRicRWqXP/Viy+LFB2UOhcXs1hSl0kgLnsnlU=,tag:YiIM2ju30W4iJpGECj/eYA==,type:str]
    username: ENC[AES256_GCM,data:tUyia04=,iv:1qJO0vZeyILYFc8oGH3496nefKgjISGsZHUSGjU9btM=,tag:ol3FJiMQxYXGJc9Xy2quAQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa1A1WElOUmRYT0ZqVS9v
            YlhpWGYzbEEwNnAvTkpkcnRYVStzZXR3QmhBCjIxakMvTVd5UWJxc2EyeXdhQWI3
            SFNNMmdFNVIxLzJUaEVIdHRFUEJDSjgKLS0tIENnRjB3dDNQbEtNVjg5aHRqYXlh
            UlBwZ3IxOFJPVGhtL0RqdVN2K0FCejgKBOR55HwL5IEsPKXTdprT2kAHZu5YUDE5
            bR5t/eLaqIMlq6pYt4XxpyLYq3EX7JSz3QRZvMz1w/EkO70mDVSaZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:07:55Z"
    mac: ENC[AES256_GCM,data:KOGp9BJSvMvsFV2OQXJjIDoGQwdtdQvdEhgWHL2nSPfcG9xvVIAeA0SxD2JQpdLgzuiMyL+s7zjoA3WI9KnJh0sKKpv4ThNE19vns1A+TnwDHrqbyAudimsisPHbwTWJI37YaDVtMLibctCpY92LMDaiu0zvIGrI3p++aydaX3c=,iv:0pm9a1k1ktQsz/zhLde/Ws7ZOv5AeWT7LpKBunW+D8E=,tag:1EJZY6SJ5iku1Ddu7pnPMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
