apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:U7WG5siNSLYnduHGKG3bDA2bpAopsx2Q91YcX2efDpV2oKFVfiFL+T/LLoPlsJOoOGMa3QJKNxmPyWSU,iv:w9cvkbeLEbH4jFPvV5pqvdhKLeA5pnE2ZVgKWbo19fA=,tag:blzpgde0IRuKAC2Dp70MmQ==,type:str]
    username: ENC[AES256_GCM,data:G3XFB4w=,iv:WUbnAvaU6lTbBjCcvwynWZKEuVtB6/uJ2FMpGm5cK5Q=,tag:Z8QNvqV1leWWQXbaMEh/JA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5emRRQ1ZNaEZ0c2dXbCt6
            Z2laa09UK0cyekNaMEVSSWlzUGl6SE0vbFRnClZUUWVvdGVERFRUT1lvUSsrcGND
            dzZGNXAwd2I5NVVERHY1ZXNEdDNpcE0KLS0tIGl2SG01VTVCWThoc2g2aCtLWndS
            TmhEZnl0Vkc5VEZEWjF5R3ovVFN3SHcK+K1w/nzEVLvrb6GMG3foVSp+L9bXFIaf
            nUa/D6nINUnW5cxZgvsdgTDTA/uv7PPGl6Rgit0/7l1RM/S+D8D3cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:20:31Z"
    mac: ENC[AES256_GCM,data:ZIFhRJivS/zBN2KYCJf4pUSQoyFMoexae+3o8YRbPt6BzasrT/LJ8cQGKcHqT7tBJTnNC96Ode3liy8rN7S4li6Yf7F1cyZXSiQVkRwXdT43+1hqlw+Oa01XWnE6lTofuv2rNtbAFwIR6d6G9Dx/BehCUjQ62ynxDL5yIskCZms=,iv:+2emT7xSyuA+w5pqJqZI+84G1ejhXuuRy0yIvPmtatU=,tag:5odYQgKnj9yrYYYTaPIubg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
