apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:d9etLYbEjzO2oLIa9uMJraLrnYHYV4GQvTonEo10psJ3I86tPHNDeQ6vBAGT6sCs6hYK1iP3epp3QlsF,iv:U3kvwr+XkF2Bmv2QgRlMd6/0Fw7HEpQjAACtDb8xl5U=,tag:RCF9vNkT5DOaejkmBF/ErQ==,type:str]
    username: ENC[AES256_GCM,data:1BNwg2Q=,iv:5L6QPsdFd8dlyfj0Ozx9ySazVZaLuRE5AncFdv5pexU=,tag:eMBPfstmpekNqeWmJZmy8Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMzhTSDNJYlBwLzdFc3hx
            TTFwMG1MemxTY1IyT2pVNDFCbzFiR0MvZG5vClZJSzZySk1zU2sxSnl4WS9qOUdk
            RDFDRXA0Y09vOHhxOFZTSkdtellvS1kKLS0tIExxK2luU2pjNWZzd0VwaFhlYkxV
            QUdWWW5TSHZJU1lBTXBGTlhuZTZ2R1kKnTfZPkg4YiHtEMz82SlKYZ1lIRrRBcYZ
            7dhqbwNFpGqHmZJ5/qQiuD7LlyZRKE02dFXOGtLAoMfJ2dnhPCJttA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T14:18:41Z"
    mac: ENC[AES256_GCM,data:0CmqOCT7k4n0zWbvwDInqPNyFQ2p47aQjOzlmocRs4L3IXldyy70QoSbhRKz71lQMS4jbKK9eyiYFiAVY2cSchGr69/fOu3J99aeZ+anpt+xA0Jpvj60/bzNtJMc6EDsBDe/MlvKvN674V3Pvy+JkPUFB5XYy2tJvUva2t5GEyI=,iv:rUOlzM/nRGKRiuUNDgur/jHFbXCZAvPIRRaAH6YxjU0=,tag:rFSV7KWGly9bf3kJsxiqiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
