apiVersion: v1
kind: Secret
metadata:
    name: ghost-secrets
    namespace: media
stringData:
    MEDIA2_GHOST_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZxO81+rAkom7NYxKC7lBsJc+nxJFvdxqY5iGAIo/H+k=,iv:4hW1UMtE/703wxZrMoWTQrVWDG1L/tpO2LBTq7Mk8og=,tag:m+rjaKAeEtbU4vmPOwLK7g==,type:str]
    MEDIA2_GHOST_DB_USER: ENC[AES256_GCM,data:kOCHhJ/l,iv:10ODbnd/4SrKGeF8+5nVYisxEgZDvmSIGEjW8nrIy4Q=,tag:d2gOgmZ+d+lL0HKq9uea/w==,type:str]
    MEDIA2_GHOST_DB_PASSWORD: ENC[AES256_GCM,data:gRVvc4nx9YvpfcuoECAI4cQnYQFsBppevqPY4DnBO6A=,iv:z60G+XApzE9FCE0EuhxxWgVecUTshQTsFy1kFaM+zFE=,tag:fdPxGhBlCYQlQl8UNS7JPg==,type:str]
    MEDIA2_GHOST_DB_DB: ENC[AES256_GCM,data:TTJRVQia4RY=,iv:LHFvtnt8b0JPzkUIdGSyxs4MyYrxM8GJcEhNPNMHTu8=,tag:37lzabfyel7WD+zmBsDwOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWEgvakRkbGhadHNzZmVZ
            SG5MU2U1RjhVSC8xTG9LeFdreFVGZWFsYkdNClViM093WWlVb1VhQnlnbWJLMmZE
            dWdjcHptRXJhWnBDNGl5cjZuL3Brb3MKLS0tIFJsaHNWU1diZ1lRaWh5a1A3bTR1
            OTN6M2ZxUVhQOW5Bd0QwMWh3enNOa2MKbV1t26KrwGrnWxQVp1DWzknBGPaPyPmh
            EEEZCb2zRup7wnPlE+wQVaDEW2Lw+BaykLcyG//kZRkEMbRuAlaNxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T11:09:36Z"
    mac: ENC[AES256_GCM,data:Gx9N7n7cbGmYxpv3bIWaRyPFhqff34Xr6KQqaFnRKqR2FGCVVCIJix7HCMXHf5xKoKmTR/1hGEkCalMzIEdv/dLs/d5FbTi0UyfJHWdpFNoPX+YUBdFgTiYJInzXtpwDQYk/Nr6Qb+pSnnSjrhCYvlmT+dElSx/rKJF0j4DAXBk=,iv:WN9DbgOlTAe9ulWzAwxDpeCV7xL9mjr8fOpQ/EOyZm8=,tag:77LHp+ppN10VX7K2BQpJUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
