apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:cyDDfFfCYngjf0x7M7Bnir21jEdqAjqvwMAV40IpwVOMV7A=,iv:xqBp4eb7zpxinCG+hWr9QJ+T8bfevayZBNLS5Gjn01Y=,tag:fIYWrBrpZcPsIq8yZf7V8A==,type:str]
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:B9OF/1DSrpRjsf8LVmdrZ5JGBlS4bwe5H4IKiqFK,iv:6EHVvMmgJwoLjit8Fo5/7LD6G4Ulm6FrCZDqlSYAaJQ=,tag:jUKzIS+plXaU6ZyPwpX1Zg==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:8Fd+awmVT6z5bL5WgcmlThT7xDTkLrLnd85LVLQp,iv:Hzxg7NNGdzpc4N/MhN6NTRG1MqZ3JrMbG8Yu6YfT2Sw=,tag:V0tUb7NQ9Pv57iADPtm8XA==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:PC32NBr27O3FbyNsVhvKo5eATBKF4enDzUNN+vef,iv:+UUzpL4FvJ8z8Cr9ThVn9g9o8sagF43YYia5mRHqLJI=,tag:liTgiPxRMWeHDmIm5aGMRw==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:TfuAHSVcHz+UsG19YQqYcnKDqWgEYgz8mffYCpcy,iv:cv1eQ4bCkcenVRlQe6BBZA19EV+G4Gjqem7lEjdauJQ=,tag:+G/auMQsoCQUWzRyWrDm4Q==,type:str]
    SECRET_AUTHELIA_USER_AIN_EMAIL: ENC[AES256_GCM,data:UA8iF3oEOlqY9BVOETr0VWmeoehZ1TgB,iv:RchFrsGGJc94bJDzREAkFbb6r/19nz9dcsmU76FZWyc=,tag:ocH2boJjrj674/AcnS1gfQ==,type:str]
    SECRET_AUTHELIA_USER_AIN_PASSWORD: ENC[AES256_GCM,data:W2iQhc8Jrxm61LiLPWohwpAIyZPgekz9Hy/lxUr6,iv:3zc5S9kyxAEK7a4Aswz/F6Qlf7q7HavOjesHFUFzIXI=,tag:nd0mv63qE0Yi3mRfaG6Q+Q==,type:str]
    SECRET_AUTHELIA_USER_FIQRI_EMAIL: ENC[AES256_GCM,data:Yaor0se1arnL63kziWnHRWjtV8VEpA==,iv:GlwriOqGIAlsEA1tATLXsWSXjGj7nuLylAc9gvx/8N4=,tag:p6x/OrPKCf0N567eWMvvdg==,type:str]
    SECRET_AUTHELIA_USER_FIQRI_PASSWORD: ENC[AES256_GCM,data:SBfVxFWixkY6BN8K,iv:eguQQVWDcQ6eq2S/xrMyhmeIkL3LD6AjU+WdWukKkSk=,tag:FKDl1VVgHm/Ie/9a+gsV7Q==,type:str]
    SECRET_AUTHELIA_USER_NURIN_EMAIL: ENC[AES256_GCM,data:R11AEAm2NwBxt4FxzjVQt4shLBVggg==,iv:Tw7i6TZDhxAjrNylvPdAKpjIhklN9zVObTRwNm13yuw=,tag:t5hAYv+xxAbp2NMyLhS36w==,type:str]
    SECRET_AUTHELIA_USER_NURIN_PASSWORD: ENC[AES256_GCM,data:CrFP1dzpwR28e6fplNlkZp9zQOCRvdFYvtRRS031,iv:jgu8Ecp6RxLpTm1Fb76vNbi63l1c9es9cTjdc5Kbyyg=,tag:iO3Ofoj1uDYORwUGHYGkGQ==,type:str]
    SECRET_AUTHELIA_USER_VISITOR_EMAIL: ENC[AES256_GCM,data:EffDI/zN2o22UPUTvWNgmDi5VXaEqA==,iv:Ydd0W0hPj2G8T1D4OL2GQCbZA2tQhUcEkQr4c8TaT0Q=,tag:9xbEM4Y8scVatLVYPIolFw==,type:str]
    SECRET_AUTHELIA_USER_VISITOR_PASSWORD: ENC[AES256_GCM,data:+kx4s/dQkwvN+L/M8ZPhP7a06bnsujNbOAmgd8rH,iv:UlS6wDEWQ119Qo+c62Tepfe7MtLJJ9VzlCu7bE5Z0T4=,tag:B1/J3PN18RCN0+/oa1HJcw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cc1X+nHsk3qMB9YPfAxErhtwjM41VTwLxBHeF/93DlDQ3sng,iv:KRCqGF89o+4pPZD7nkN1c34JEjCa+QJqepHxPansQmc=,tag:cDJSJW7X0l92Ru5SRJw2jw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kVgIR3eu0Jx6LiaKqnr+GP39Jxc=,iv:btA8rfIl50R2vMideBFclIVAmisMxWqXAWwosD+NS1g=,tag:YUU0s33ftSxLE36/cvJx4Q==,type:str]
    SECRET_POSTGRES_HOST: ENC[AES256_GCM,data:v6RLI6TrwH8yFl+6JgmF5N61jkKKUQtlNJGgfm/FRL0pnzN2tXc=,iv:e0NCnhes3ZWJremLhiKho6P/Tlq5y0IIfPBL0etHSrA=,tag:LeX2bhHa05wKkN7AJLRK8g==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:nBSCa+VxM77tUceyH4rqMj6O5MuHf1Co7pKEDQ+z,iv:VhRAG29cItJbRAbYXoT7k+dcZ3srNAVN4HUogXgF4L0=,tag:ppYya9QNVMcE+3ty9s4Fmg==,type:str]
    SECRET_SMTP_USER: ENC[AES256_GCM,data:hdexxQAnXb/5K4ALFhV2SyhoKAtNTA==,iv:KdM+MLSTs6gmN04CQK6lGG0v9YMv9/cXmWCK8NhQne0=,tag:eGvW6PHlYXAxPZqhzdixNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYndEOS9KakxhTCtxdVdQ
            UTlHS0s3eTdvOUIrRkcrcFBLVXR0elRZY1RzCmRlMzd5NzBpbjBpYVlYZnZiMkJ0
            RkFLaUZlSGFyaXVpZUFPM0U3RC9qZTgKLS0tIENTb2lEL2VtQkxrTlk1MVV3c3Q4
            NjZzaXdwN2NEbXZuRndFMDRZV2dpaFEKPjgQhmX6dQ0GjeHLOikssEZ9zFCPOcZH
            Sm7xP3569oRkJst/5PfaoThTvnaKQsf1G5vSAEwsvz/g2kvbVLvQ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:20:03Z"
    mac: ENC[AES256_GCM,data:Q5ttlsV+q7QuYACTa7jAR9ijt7qCGpyojpwy6R+PNfXsx/1wwJT6W7YQshazmte4/gJPBsyFI8SsBCBn8+VKzcjwv/+HhMn0IgcBU5ueYsqQTP4E2fufRnp5Q2MTeag1ThJllO9LCkTm7cK9xJHo7c1jGSnTc8bBAd0f0bJrPUE=,iv:Q9ymIBhehZdMwH5ue6bvMHfygSWraL9pm6+Ax+X9wEM=,tag:5ePJ5EIfnRvavTaFp/8OHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
