apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:aCKdKhb+XHsixDcq,iv:ZqytCLo5iVbKBmvMVXigyFdE9u9XHA48ZyqA39151NE=,tag:B7GXoCKHb5TQnjXqNs51yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aXpxNUdic0hKTld6bklw
            WjJHSU9wSzlUdUpBcGcrWVRZNDZnN2xDV2hNCjN4OUs2Z1Y4MStiNStOZytoTzcx
            Tm5KN3ozWE9VWnJzdmVKd21RMGJoV1EKLS0tIDF2UitvanhBRHQzVlpBMW1nZlU3
            Q3dMc2xoSTdldS9XOGJxMVVlR3JFb2cK8QdHpojAUxGtIeQSvBLPiK+BqPO6dJzi
            mYj5GZLD9g71SraVcZ0OitdhsrwiooM3AXJGQGkV2JF5a+JoVXJY3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T12:14:26Z"
    mac: ENC[AES256_GCM,data:l9yTgRTLvXW0JyNEGRz8MjA635op99vBgksro4/7fpKLZEZmjZjpdmk08vbx2a5AsDRl6OuXLeeFNIcVDkWAkjG0RTPosMtv9hrxl0WOUyfBeyhJBDf1x5vyfagdA8jP/cMvshENsjaWb/Cv5KutTJqBYTaXZ/3jMgyUq2gkbYc=,iv:50IkYfwOYqaC54Xio0nRngwl4i+DmjD2S7QejSAXEGw=,tag:b4PDdVLUw7LEK2LZwUhzXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
