gaaapiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Yly+EjSZnuAAsbdk,iv:scGg9z0kjr666fVGNPjCX5TLla8gOnSK1xaB+XNwcoE=,tag:SMfscUftblXZoDpnjNBnqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTTV0SmJHRzB2aUFndnNQ
            QjU1NjVBL2plUUtyVFd5b1RVM1gvNzBNQnh3Cm04QjdzRmNKR21NWUpZbVZIQmFk
            KzBwY3k0RWs0TzVjb1hPSURyKytOeG8KLS0tIGdtVzdZbjIyaWRReGxFbTN1K2pH
            T3d5MUU2aERpRis4anNQRG1ZWDhsUGcKLaT8k+CwTGeYvHBI6v9bGYEDv9MSOUVK
            yVL6JYIadWCe/Qlp8xhVNUm2ZRxLonwj1nC60gPTtMXjMb0N+U/yPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T09:12:49Z"
    mac: ENC[AES256_GCM,data:Gqr9boGSSSsZCT1+kcajFBRoy2+099UhzddJXbVm8Io/A4ohZSuvmwwXx+yxIo46RscoWGkEf2LIOqnfKbr3XzxBBybdwQUJce0GlwVjqIf7VSgtX6pMskmPc0eIxuD2QpfX3HtYsOE1Qn/OemiW5Cmc8BYSTik46jxrjj4T22g=,iv:/ZpTtIHaYIvFcwOquwCX32yJLwABNDYDKj2jGo9l2Io=,tag:4igaVxlTlCVGWD4vijNFFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
