apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:z18ZWWz7fvOGK6YG,iv:oQK9zFsA1foRQrkwBxPSwBlA7fc8wdhpbyHcb4hLXo0=,tag:GL2jhmopJSEuz62Vo+xEwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkJHKzNyY0NPTzd4Z2FK
            N1EycHlLSzBzTWhIaUZxNU1LbTZ2MVJIN25JCklTNmdmRnl6SFdQWXlyYStMS0VY
            R2ZDSE9EK2hJYjZVVnFLQ2sxQUhDdDQKLS0tIEZxaEpaTnhnL1hHaG9YUEdwZG9s
            bmYrVmQzbDJiNWtOcUNYbUc0UStNdTAK865gszuVXkoTCqFdx4ucp3+zXCknDWW3
            iZrLNLXrdBSQ1UAwIT+AjECk6qKropq1Q/tWd6PxpdQvyiCgpSa5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T04:54:33Z"
    mac: ENC[AES256_GCM,data:XzXbDMrxbUYrhBd1WXp/RgQE8ecIwvEWv/ejguRnlaJuMNaYQ3GmHDS/YTPDtV9UW9S3YQM39pkH7J+DSgKJ+yWoOe5HGYp55p4H/mLjakTXa5yzYgrEJ9rgC7Zq0aYwgnfR6pKc3Jdgstwp3d/7fjru7jpGBy5lIb+yV0u9s6k=,iv:E0s54yJOb0Sb7Tj2s2wT5jnSZoQqhUTL7+ErQV1EaBE=,tag:ZYFWUStfsz2YQtlQZk1aTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
