apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Lzp81QeIBIjZqMpV,iv:I1jvzVJ1goVKPAYQGP1CNch1E63KXQmwGpICohWG09U=,tag:inj0QGMtHkjjy+luJwGXZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQUtZYUZSNWxQUFdrc0ZY
            UVh1elJJTlFLWVNzU3dCck53RlNGQy9CZTM4Ck9DNnlXd292dThHWkRzY2xDVEp3
            NjUyQ3ZHQU1NU2w5UHUveE00NWJNNWMKLS0tIDlnNndLcU8xend4UEcvMTVWTGls
            TllRMUdMTnA1NVVWRE1ZeWtoS3R6YVkK6a/0lD/eevVuOt40LtdzE8jFcdwlY3IL
            OCeasWoni5odqnEHGa+Gm5yol1NUx1XjvBx6c4l6vY0Lv6VznRftNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T14:30:28Z"
    mac: ENC[AES256_GCM,data:NS9f+zsxQC5b1rZ5dwwN2zcvdojGGuzDURcp3S/In7nAL/nq9mO4alYoJvi7mYE9VvX4FTZsE2fZucy2R4Yb/gRybePP3w45E39n8rKHSsdKvvcrVjQCYXaeKKlrLYBXR0Hq0vQzIO4H+pgJ5ZIHMTGRTNHqZnovW0rNdT5QIRc=,iv:Ae66BMYiIR823LyyOaeQbqosPbTiyIJgJDC2AlM9ro8=,tag:8NOPG1JIWDhHsu4wIQAzCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
