apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:PksQuExIDxN77/JZjxwBB+ACCkW7JIJvE3mBbo09wt4=,iv:O4l4ZpmjYVdcjZeLS86ZwI+//9qSfbgpgSIf+yEV8EE=,tag:lXIy8mvWCHyqmrMIHgpOhQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:n7ivNQbb7vvnfwhBALGRq1+8HVvdTsi632Ckr/YlfBM=,iv:9GpJuSP6vca851Gx7Wp4vAUAKo86XXXBADYpyb/LaRI=,tag:jJYzy8HJD+OPYA9yTUTyig==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:KGRsPyO3xOMabQpCuXMBl7BnE/XdUVornDa3+e8cHls=,iv:nEqSmdZ3eWkDkWV/1gcLrA05RagR6qMJMt4/dAeTuUI=,tag:hltZmRshP0at4IcDmTtvtg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:fHEj9Fr/+EfhDnm4ww5jI7chPY0GqHL/h/bprEeM9lc=,iv:dsctCjCSoqF+y5kj9sq3JY4ghs642o1dS0fxVSIeT6E=,tag:ZwJnG/FHR0Vix/J5TL376g==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:oJhCeSRe,iv:e64jbuLTGlCDSqBfp5jlX6I2ZJixBVli4jiwG1XppmY=,tag:ncvf3kKY3roxS9FsmpwEDA==,type:str]
    AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:qxdRcmdjD5cyaIUUKw02i3DX1Rq56zgJsNhoDMcC8pI=,iv:J/OAllZzffPGqcZtPrmLq2xCs0TcmxYSsTxgedWZ8D0=,tag:q5EP725p5rWe3vxEmUb0MA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:oE8MwqZswsySMgYHY9+B2T5ybttV93NJnGChN71Ah24=,iv:8PmvmWknRggb2wIslnE99wA+IiVTQWTn1gV+RSkMjf0=,tag:Bzy/ISc6iYVCkRWm9DNfWw==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6nLvVGwi1khjGVbdhAU2zBzopfYhITiXjJVldm1q/ZQ=,iv:p3XhU/3UE5iX82jGWCgAaPWRua30i/nC7hukJC9nqFg=,tag:HNREOglpYJ3k2QRr/y6eyQ==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:NwYkIRuKhtiJ7cWUtU8IPI/8FjtHDv/kubvpiwjR2A4=,iv:W2jxM3oG43uwyeqmlTcqgrtTHzPxF6zjZvlSdw0qGUg=,tag:jKA3tTFwqjxbOpImpf/SRw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:K19FHO1zWrrq/PEpPxt/8QE39YbYGpZpke+NerXheo5Gq9I=,iv:FaqEC2Fe+4wnt5Ru0AEyIUbNWdGMs0R6B6YgBxYbwwE=,tag:eqOqWM6kG+sbNa94v8JHaw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:p1Lv2CjxBjkzSXFqL36n6J3qOrdwjAKMeuMdTDAA3E4=,iv:gBPumNe24aU6z8/iM2fngOieuGSthl7CQ6jk9ViEskU=,tag:Wul6YrMQeaqkD6R4xA0cxw==,type:str]
    LLDAP_POSTGRES_PASS: ENC[AES256_GCM,data:tuk2nrrDIdaabpvwRbqAxEJO89ijm+YXGACeNIrs8m0=,iv:71oFPyST2MQ6BV/Y3Ia4mtxdsordzslLedJrs7olkvk=,tag:DV7cnfo9V/OiMj1IyqiqYg==,type:str]
    LLDAP_POSTGRES_USER: ENC[AES256_GCM,data:SCYgV5aA6dIRMI3GYA==,iv:mwf5U62egakMCL1J4jMos4JYzeGqCT3HFYT9OZNrqr8=,tag:NDK5svSswWJy16vyo0x6Uw==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:7gD+B9WzfUYfIxZW9/OGo0e5vJUQmRgfvx4dNGUTP7I=,iv:S0/nZh78APQKn1P2F+tADm6qxKPs07gydWGlnvlUCCM=,tag:Wxd3qkNfAYAsj0ocgs8eig==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:WugTVb4c8U62SJn+mQ==,iv:EhqfO5b+7W6ITjm7aMsRBiu+Y3YJMuY4jWRPgAvP8LU=,tag:gog3FO7xwjZyAVrVsRAogA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WVj1iTSUiggQE0avvHRWFTjHI3QywjMkBlvtKQ5sv+o=,iv:o0+4kF3vPm7vM/s5hBXhOz/15ju6UzNAwIFXQ4ean44=,tag:dkc4prQ6OdLhZxZMyK894A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:EyvcsSk0Ox8rEJD2hJEOdBXhZjrmgwGTgNUqvrZ9qdzAZMQ=,iv:4pnBbOJXgwBc0JKaIIGDeQb6/2SsvXe2bl9WAXu0GOQ=,tag:4wchWQGaYZbRcpplMA91+A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:npBcjVIe5Q8IvsyW95y8yvyFyOpg40J7M50KjndkqXfz3ZkR,iv:gtGADX5GdeAwRALw/MCXBDF3LgJaSyA6fNdfmeCjjuc=,tag:agEQUM8/IpYNfYgquDL46w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:f9ZJXFdynB3cRHaOeMG780qWIR4=,iv:MqpQYf/oYNY1orBUZewcxYgVohIxm2dXn3sF4GnDjAA=,tag:R87Qpger6LFq681YW+u4tg==,type:str]
    SECRET_LDAP_ROOT: ENC[AES256_GCM,data:PiCdn8k2,iv:pKb8opTgIOv6ivZsGS8ZecVNo745EaibT8B5menw/00=,tag:Q3sAbK3B+SSl8bkOKRqW5g==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:pcmKLHQJj/hCnzIXCjcn0eBCvPGlay4aCYwjHhgywxM=,iv:S7TwM00yR3MYpaxhdxNaDw5876E+wEvEV/Go4LZ10fY=,tag:GmR9nflQhiMaQQtRYOyBgw==,type:str]
    SMTP_RELAY_PORT: ENC[AES256_GCM,data:MVwbHzI=,iv:PgpYa4xU7WAwlpd5wzyQal9WpJcipB1EbIgaHLGXlec=,tag:/eE4eNr1mfFhM8ygp2uCEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMHkzZjE2NXE4aXlRRXdp
            cnJpSDF3WkxKQnFBUHI5OWpsTlpFS3BIakZjClk5dEFTVzJvQWt4QmRKM3NkcmE2
            Qm9kS09OTG5hdkQ5a1EwbmY5Wjg0SlUKLS0tIDRZbVdvaUZKZk1wR1NTdmNoSmFn
            TUtJeE56YWMvWFZvNlhLbVRaM2g0SDQKarxdkbPuKuw6rWJzvi53Xo/4OGICzJCP
            fnb23bLJJ79qem3kiNHbsItMe/awKpOYnM0PmfbICyUPXaLkCPXkxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:10:45Z"
    mac: ENC[AES256_GCM,data:EubuHekgzxFlxKAwcqE0OZD0KpEySWcH/H8mSFeSeNyIwDW2b6tCwPOcd318vOZJo0s8VvxpvjbsIPQwJuydDzWxVtFR5aCG6nX66owc2AtchTNr08DIkeC/FDPTXhCUaJQZwMOWIY0H746zPxyqFfXMQSoPiyVJitjXJfRpAKc=,iv:EZMAG62qx4Znm9fhxelkshYNUAk4E/1SRtRVfY0YQGU=,tag:JIK3y9oZ5Otgtcc0r4xfeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
