apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:N6lK3/3QO9L4ABtVb+QXWq7yuMe55Uw3KwyZ/852kLE=,iv:Iq/Ab4RwJijV1tow73gTB17OZoqgqKM57dkGe3WG/ak=,tag:e04/H+YM7WraSUGnynQqDw==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:RJHilmdPMubhU/42LmNdtxdj9RAZzKSf+i3ccQuMfE0=,iv:NY1GWh5mxLwCR6FTKau7odT4f4V1la3qtWBaosP48r4=,tag:VSWVNFA8hBFL2yDBYQU+Xg==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:zq/cIKm+Ir0tG7TZDmPcwk0bJrHVkDQNAV77sLdHkf0=,iv:/G4eDMD2WaJ0am4vN+x0GjV4unkmg6NF8Q313Xzj9u4=,tag:C9AAiuxW1PiSJ+2SH/fEgg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:79zE0fxbwHyMK6KgKpVbGvr6JSU9HEq6XyPUdNpqeKw=,iv:QxAG2woPbHdwXrvYQMVb62c53FhmRjoxQ5l2sqmjfEI=,tag:HdALCTkA+weBhELRRGlUoA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:XPYg73SU,iv:ZBt+TXKt6kjNPHVcmCYCeLzE5ttnAYCY6c65HSal3TM=,tag:tAy4+ukdVdmV9fYqUGljWA==,type:str]
    AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:OhcoLEO+EGrRJNpSW/KhAL13M/V9x/FtizFKM/5uALw=,iv:pRmoyQvlh/3dnhF8cgt7d2IGZryXheMRXboPQfoBpjg=,tag:+U5YdT1VcFVGtAkYNlvGfw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:KvHgKYwpD4XrdgkFxY3/0IRN/9jiLW61DJ/m1rD1KTY=,iv:SlQGj3JtY3ENHgc9ENrW1N1XsOncMgwYGhOC3CaUDIg=,tag:R9c79akWUSl6EiZNRgzoyw==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6++zkDpeG+kUvNcQIvZEY6T/ofCzqM9uwykDPcFJsFU=,iv:H5jE1e5lgw4cwszPrXmm1G09ggVljPSg+oyvjUyjAF0=,tag:I+XbSG9mmY3S86P4vQJVeg==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:2pet6cXi4QYOs5EE5GYM7Nz/h2yZ4LZKtROLesO6gT0=,iv:q/ZLyGRgdI6nvuLLx4B9LrrmDs7araWJ1morNlwujsY=,tag:r01XDB4dreS7hvficGAjEA==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:3eZq9QhPFnAIzsN7RfdCcqNuxnASUER8EURCX5gAmjSarr4=,iv:QH3zQ1pNkPSSp2eTFFG2Yaw0Fxz4cM2AReuHgvwvfGY=,tag:pSCVa7LNAKleeFf5QpPSKw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:ssdGJ9NgyaOD92uWk1ikEXv2TMq+QfyiYnJsqJafYbo=,iv:50oFiOSRbkwh5YXPRBwzI4ETOo/nQs2M3RJw4ZEy1Ao=,tag:OBgGer+JVsvc5K4LUYxWtA==,type:str]
    LLDAP_POSTGRES_PASS: ENC[AES256_GCM,data:uoH/WmGOSihkfl/tyuEocYo9HCrXclIbbRdPwX++7KU=,iv:wGqFcKr3Dys978BNNOxSTnhKlkor9oTOW78QEh+3lik=,tag:wix0wHrWULhSZHjAS2qazw==,type:str]
    LLDAP_POSTGRES_USER: ENC[AES256_GCM,data:r6i7b/ZlTj0/mwzIaw==,iv:IOqkXO2hIw7SyEyZpNm7liX/E7Hd1zBa+iVvg5xj9zg=,tag:hoivUOfBNpB4/x2qO/+zLg==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:X6l/mVbc/kmZGbyjrUNP7qEP1z7OKHRytmEjWx0krMI=,iv:IKB+RsZr7QE6jeDvZKcE5lc0naNsDauHXsEbuQKZlTc=,tag:oq/4LIQP2mYM1oL45I6Ykg==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:rgl6Y9VXz5Xnt2NOhA==,iv:O5jiWcG/mhJaNnrztHtX15wwLfYWxO8Up+IYIlaco+E=,tag:/V0E5RZ/6i/3ocuowhh34A==,type:str]
    MEDIA_GHOST_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:kOL8DYy2LqEd2ABdOuCfzLgFDafAg1khGOWn+isjZLs=,iv:5kH02hqczU20SN0Sh9rhIJE29RjFxDaOJYdBFGEc4LI=,tag:/Y40JGAKbXsvVhJILI8adw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:b6tOltUImsXB4Xxq0JCfvmmsG7sxP1NdiQ7aVnCKLSI=,iv:S/2eDWTp4SrdU3WZd/1kGv+LrN27/U27kYqcpqGfX4U=,tag:WklQRcSB6fwLrlXIZSvapg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JSMiMqQ8kD3snvLR4gUx+IwnoTuwzlxUufMKxv9jWP480Ds=,iv:5Q2U+g0q1ynJsBRFIAjIADyUONUdDfJZWM3/hfBrYZ8=,tag:SFKRjnv8prJxFaFvTsPGQQ==,type:str]
    SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:FsH7wMfoTynq,iv:fKUhBFliBonRF7Ya0smCMq88BZoLX46lQWe5JiQ1nyY=,tag:itNgTPDZnYjsnOdedOee4Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jxw4ajUFe6zzBsc2fF+YX9IAARjpcFQB89CgFX07BDt3YmcB,iv:7ovXj8GfDUG82Qme5YeEaElwCIKN7kxzlH+BzqUkKK8=,tag:OMVdQgtj5lOGOIQatfUdsw==,type:str]
    SECRET_CODESERVER_PASSWORD: ENC[AES256_GCM,data:dulDM0z8ATCRFrK4jOX6/phziA41kffxwcHI89p5/lQ=,iv:WG3v6TOvhQb9HqgW1lkyV0ZnRBRMmD8BtqQWhz1ALxE=,tag:4nb18gNd2gC5Lvk7puPBCg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:jekBo7LyFbmLbWmEi5yhWQ==,iv:hK/ZJpVnP12srxET8ODM2E2YCcPZdy3syR2QhHEkDAw=,tag:3lblllJMgvCWve7q6nVsTw==,type:str]
    SECRET_DOMAIN1: ENC[AES256_GCM,data:LA/SngshGvKjpBnGjaobzcsLtSy6dQmPB5w=,iv:/JUKvRSmVooR6AJFux7LQFWIOua1AJd78dw7uZOPtFc=,tag:DhaoZ3Hckw1wfJFdyZzpDQ==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:hdrSzJqZ1oMmhAXyemtrU/uEucg3vuPLGQ==,iv:AtJAihfP8eZCm5Z6Qzh/fqfFDExVRj0Cw8YeGYB2qVg=,tag:LYJRtxCfxr53gJKiHwDPZA==,type:str]
    SECRET_GHOST_MARIADB_DB: ENC[AES256_GCM,data:QDYTrr5y,iv:CgvF3BiybcRSR7iglF95YqAX5E9c/7LW3GBRzRRHYU8=,tag:3DKAwtB3lq/17Lc7x35tKw==,type:str]
    SECRET_GHOST_MARIADB_PASS: ENC[AES256_GCM,data:BI3w6hxE6sK3WvzYijsx8KSCqF+LIC2HY6BqaKYEdbc=,iv:ZQtkpfb6WZPxbugKKGFnSgszSiqv4BiQW95xmKYrJMM=,tag:TSdcAhEnryEqpCvtp2RqQA==,type:str]
    SECRET_GHOST_MARIADB_USER: ENC[AES256_GCM,data:s6gam6sh,iv:gvo7SmzV2PLZqYnMW5jF9Kspl/X7RMAsRWFfPDma07g=,tag:hGHYE+SAytH850dnT7ch7A==,type:str]
    SECRET_LDAP_ROOT: ENC[AES256_GCM,data:6SYt5tOA,iv:OWAIGCvMrK/a8dSmitCgHTt/xp/p4SfrOUS5zAb1SyM=,tag:5brBtuxc+9EnPJ9zPsmPpw==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:ExoKLTamXW2XwtEUtlnvCjh/mVHZC0F5tY+cr7NP1+Y=,iv:cax7Li7b1AbBc0txWG/FxcuiA23UKutFNued0gCQ2Y8=,tag:/imlTN+me1D35ozeLRB2LQ==,type:str]
    SMTP_RELAY_PORT: ENC[AES256_GCM,data:75aSV0w=,iv:+cJREunouwWrkVnS6itJginWofHOhamohxKAp58ehMo=,tag:fMmmO2JMmjSfh6Og1lH4tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR09CSTc2ZkphRDZDQzAy
            TmdXSkVhc1RGTWtIb2lFZGpGMUp2alltMVRnCmNXdGlua2pBRmN2K1krcGczK0Yy
            WkZQZm5JOHV6RG5pQXIzU3I1K0VnOGsKLS0tIGluakpGNEY1dU96alZGUnhnc0Yx
            aGNUNTlNZEFmZ1oyQnc3b1NReGtFRGcKxnzeDGJN6U6YBe01YiooU0qJI6xIapvw
            WiMFhRy3NdvhJzVvGEpVmZ5JoQNxkqUc2dxrXaETlbWLSYqCtwpA/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T02:57:49Z"
    mac: ENC[AES256_GCM,data:TTocMo4X6wvwcMsyCDYR3078IEzy5M7kFzyO+j327JAgyNpqxrP4aNlgeblZnO1P4tZ2m2xZlHrWORBnufS00n/RB49RCxs1n3CpO1iAb6fbbjcJWGMxCDODM2IoVEs6jsbghxS3IG+MvdpXZtRMHRozq8sg6Ms25Kq1Iow/ygI=,iv:F6h5Hv/0Gg6UZvXw17XC9w50ZPbvDVZ9DRD3l2uCmME=,tag:r551cTt+GzVg3ckHcLzG4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
