apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:64G2fTgUslaLBFYQ,iv:5u1NXSQhiwPy1SIIWjYAIWP5Lj2Askq+kMoBGtx7/oY=,tag:ECZTQtlMmCcR0BpddvaoZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bEFiZlBKMHNraGpCNWdu
            T0JtMk5hSnZHQ1hVSUlTYkpJYmkrNVJvblFvCnFpMUxXanpUdUlTWVdFUkd1anY2
            NVJwVWFxdU5oaWc0OHFtemloQUs3cjAKLS0tIGN3VVpJSTF5b2t6b0svSHVyY29E
            R3IySHRZR2JYMGQzSVNPVXpKSjlwZDQKc0jMyySTA5lQCURUrdMM7OTgeZyTT7uc
            oKU/QlTSu0NPHU6UYouNSFEiLYAdMyTpHMCBKEm/75LXsFPNDFlPFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:26:22Z"
    mac: ENC[AES256_GCM,data:NkG8muEOb/qnhhaHNdaU72mR6TnpYnxRvfYpOHbXqyFZtJd5hMEEWPOOrlVi2Aup91/7BJJu0/Lqx18HX1RDfyXf0j9DPxPLBg3a2PLDvk5Q5X1ZhO1hPVRsrGwCZNgqNztz+D/xO6DZ9g9HE21UzKmNzyOz27/kdg4cC+4N17k=,iv:4PxUfk/znjhrdRCTW6Le2Aj1cZ4doC3OV2RE3bHYHSA=,tag:yEe8urwnnuwZeBLZUF1hDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
