apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:e6QKSAz4NV8y13yR,iv:BpA1HzSOyW1jjMSNeYfYLwy0Cb5FqncUTlA1olR5AmE=,tag:ogkpXAc8OOxsKJRccMryCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1U1WDNkOW9KdXQxcE1w
            dzNzV3dsTFpqRmFrdEhGckdaRzJvTG5CREJJCjFaMnc0WkRyRDhLUG1QNkNCcVM2
            UzVMRUx2STl4allxeEtDcGZZWWxqcjQKLS0tIFJ5NlJjVkFwM253NzBndVAxNG14
            ZFJ1ZVhiZXllUHRHT1BsMSs3RUo0YmcKFm6CpdCOjF7KzrG6BoDQq97EG6Bx/2qz
            gA0L/nPzJ3um5j527170qavFzk0i5iK2As5cGzR2G7w+JUtERCa1KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T03:16:26Z"
    mac: ENC[AES256_GCM,data:u0HaXqiE0fIKqKH3EMpWwWfUCgTGaNusr5KqmMHZiat/LcZGmfttUOf36UpaXM86OxmQU9QYGhwBN3KX4EWGdRpqJXYOMvtuKDwwQZgm9AyHaMYc3d+mGjSN27t8o/EWBNmQb54dS7gevbuSlG+9pBo649bsRsAyxI29zHtR2oc=,iv:nw4uynZQ3BhWCERD1xPY1O98SwyL21l8FJFp86H7laQ=,tag:YJPU/Ixuy3QMlBYRiMeCPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
