apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WSao93LP0Wqx9UbrqbYZLLbOCfJQm5l00aCUA/Bi2NdVUXA=,iv:5/sEV0PVnEFjy7Q72Lg8pEmfwf6XUNUUtkeHKF7KaHU=,tag:Z9/SZjfniO+by/PctY9xaw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4SCM8tiqi24hVJNdzDaGB+cir3N2rl7U37FOZtARsYlyJKsM,iv:0vozlMHaEjotFYrsB2BRrd5P3AqGrfKeKOeAI4u6/uY=,tag:xR8cE3dcvl/4aTNhaP86QA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZpBEjluStCXi4Hlxz+PhToqmA8Q=,iv:SZ7zYOqcZ9pVEdhYVYTZmfyTzUqKy6OT+YWmOe47BIo=,tag:mP/+3/Qz2XCE6Ia5uLvlEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcXB4N2l5cDBDYndlcmZ4
            Q3NEOW1TRFBOdGpOVkRaU2tUOHp3NGxYdHh3CkVkcGp2VDBodVh1cFFlMXZaak5S
            am8wQWlMSWg3RnMvTXVUVXN4b0pSRlUKLS0tIHloQ2h0UE9Pb2U4a2VLMmdyVUg1
            NnJHZTFoOGZvUDFZaUdDckphN29CcWcKYLtp2ky5QqvuAKWU0xhYLM6tvGaxjQLP
            2tkROUEtlikYz4ICkX5GkOjl0FrT6DuAhZK2h9wkDSQ7tQ156d1alA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T11:34:36Z"
    mac: ENC[AES256_GCM,data:0bcmV3hHRVJI3ug3vruVZl5MJW67GqR6VzmSSh2/qOjpb8L7zbOUiJJjUoX/Y8O+n5osiKn+GFM6OCl5nT73yHGO1wNnthLhTcvBxN/0aLVjndHtHRjqaaynSCs9/Io8Bi16b/NmbCBhpNieVR2BgI0lSVuVQISwhskDc/Fq+L4=,iv:Ca2EcJS9uRLdbIw7jcGxAeldYLJ3j0Iwq93h9aj4wYs=,tag:ApsW/GI2+M0cBul77Gfr1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
