apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:ZB6dA13s4FgzxxEx,iv:o6ZVLZzWuH1m6jWW4lhxWcXi6p7rhZztcJCw7BmPxyE=,tag:pGhdgfKSLo0jfaXqLv4a8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdDBUTTd0SlRGT08rejNB
            ZngvVWc4eDBRSm83OWtMbVYrU1RnWEJMd1M0CndXVkV6RisweW4zampXQjZPQXdo
            cDIvb3FKWmg4THVvYmJoYzZpdlpYNG8KLS0tIHVKTmJ2dC9rQjltcnI1SHJkb0cr
            YnZGVW5Tb3RLbjdpNDE1SFlZQjcya1EKi7+yjJTZrpeLxbwVyGTJ516LCOoHZX2j
            HT+bPpVcs4gpdc4pC6A87eZyYYuuZ1C3JuKy6NCJpdHjQ+A8lODGSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T02:57:45Z"
    mac: ENC[AES256_GCM,data:bcTZmlxAOd7tKMil8r2a9pAGzdWOPH0qIihf1tJspD0oACsxcrxPLlT5dY5cIY0kSgfTU9sZQ8ILCO9cdr7fTNsW8r/kNa4SBXSTA8VnNeKLagFR5K+Hn3RUkojqpMvtiVDGBO5HwG0iDJFfMBr8iloiFEwPW2vmCASd28Ygqds=,iv:HI4A1I/W1gRnLvR0oQ0FsNwElEkzmVYASQz+UT0tYgk=,tag:flTbv734y68isbnBYDSfQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
