apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:kCx/FRfGUCHczu39N6AY/Q==,iv:fgcGmQqPJH80h/ICuS3z+t6UbDMzNdxELCNplXFmja8=,tag:fkU2wpdKIIFOyHsonV6wlA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:9tGEys48/peAMynf6icwJRFkxQMUcb1zwxERVm7kptY=,iv:SBOkc+kau4YsL11zfIsh2J2Skdw5cDhJk6PZu6GBPqM=,tag:IzxMYwrajGOQivj/KcQ7AA==,type:str]
    password: ENC[AES256_GCM,data:5I2hauyvfauuyApDOB8Z8g==,iv:AQ0XGsQ3keepVztb2rgYSZpJEj8b0z9GeyMxgfHysk4=,tag:rc1kk7+Oux47NQcX0pq2Jg==,type:str]
    username: ENC[AES256_GCM,data:N8AQhAwRkEsJ4yJXTMsLVdR4iqivmDPh6JBXVH3V4Bo=,iv:JCO4vC/sBe21KRQHxm7DvRS2rNaUpodMwivWOPBMc/I=,tag:W/CLlh1G4/vAqw6no/Qz7g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlanBvL1d6UlFFTGo5R1hi
            UTVCemQxQWdaMzRsRGRzY1ZJVml3OFhVaUFNCnR0bEtSVkZpS0N4SWE2aGRqcU1L
            SWc3YU9JZGx4WEQ1L2UyellFcitzN28KLS0tIHo2WjV6cHQyOEFVWjRBbXR2c0VE
            ZkIzaWl4UldHVUJqTUtSNTNGcXNFUFUKOm8vN1XSxuZkzwNNKDGcWP3Kka5ajGfJ
            kvULBKEGVW7OQcNnzFEhXlnTon7Wx0XBZcJYx3fX5yWFXvewdxNH5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T02:57:56Z"
    mac: ENC[AES256_GCM,data:wGIlWFWIIBP9PFsy3GhMs1nvEev+kw5VG8r6jwj4P9pRjtuPckFAeDh3jDGUq6yF/XtZc1CRoHbnzNcOprRjpQbcLhDDUnqlSb+QzgodEXMAXO0ijCAr2xWXiqlvF2ToutwJJXdr4iFGPlYpa3sUAy38By2M/BNB4KURKFZPjuQ=,iv:LkDwxOA1QD80BcOjx0jL28WZg7HGPZhVguLYUEDWPKE=,tag:cagyP0OGV2I3oVPcOKdI4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
