apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:a3qZpGd2vCPhmKqbMk/gmQ==,iv:rx2WbJM9BvkLYeFw3nw8Lo6O6hfXcB3Bd8FRDFJea88=,tag:SdEOAf+SMvSggn3kuKYKNg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:RFePqNvaYOjZXEDCyVboe8qYiI+QC69egq2nE4QKNX8=,iv:Wfrm6NLLlyASFEbMhFDaogNdRxlP4ZL9AqjW1RVoxNk=,tag:RxSWghFmJAmuC6N3bhZobg==,type:str]
    password: ENC[AES256_GCM,data:B8rRKKeKxy7yefsV6pG1ew==,iv:vIRFtclMvIkEny50YRZ6pFqbjM2DP6LVemjcfAl4gdI=,tag:88beoocReUv7TTuRoPiK7w==,type:str]
    username: ENC[AES256_GCM,data:2ht2bpP8eXDiVHhAlelG55tZzgtrq2KZoFSPLdvJguY=,iv:itPooRd15aQgdfEDOFY+kzK8PbMHvpbbK3XDUUFWDFA=,tag:Qxw3mmjnZ/7JsH2lB4nzvg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d2k2US90Q3dMclVjcHZH
            Sk9JZ2psYldkL1hLRUQ0YWkzTnlzQ0xQaERvClRTdEFFUHlob1YxeHplYktET3JR
            azVjUmJpWGpaV3I2VGtQaHcwalUvNWsKLS0tIHk0aHkxdVhBSk9CNWNrLytVczhr
            aG83YnRmcHlDMWl3OWg1M1JiYnNzV1kKzMDMaNqNNRJ2PuiAuGE+bHUeiKL+rCQu
            RyTCyyVtMI76e/pZIZLRG091u75J+9aTMXpJL4czz9A+QzbyrQc5Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T13:45:10Z"
    mac: ENC[AES256_GCM,data:zomtIHTjXraU6IgFEnTqw06svNHO2GP/binH2nvlCkZaJHa/vy8tOhvVBDbSHiCTop39umdL83FzeDvuyg0SvV/m+CM5HE4kHKV0fYh+lDUGNFkoB2hbrSnxwhx//es5h3sUY9zG9PY0sNZMf8YrUXNWL7rTzgF3rHa1gxouEJE=,iv:YjxkgKELZk8pG8ovD9G0zRiCDUPWLTdAvahZqz+T8wU=,tag:PxoTDhwKm1qUZViQKuA/VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
