apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:8fVNHcYwvsR+itRcDEgtsg==,iv:cZTgDoXCu9yDF6onGWRK+5G6OPKeag0JroxaAnH3660=,tag:viU/0i8TGi4Qc0swkKThcQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:LBZ1UbxqhXTD807+48p/k/c4lzlIimbo1O8GK6OCQUM=,iv:ce9o9/uumsp/AAUMWF7f32Sb4JonQxyPAQasE+wyIdE=,tag:o/Sj8nhJ8uVgOKA9o73bBg==,type:str]
    password: ENC[AES256_GCM,data:k5KlEpXnvXNtNpOqEFh1mw==,iv:aWACwHSuqkg6eglHIPs3ZWETpZTrbaXdrcc5IGmtri4=,tag:dR4RCIE7zQ93Bg93Ntu8PQ==,type:str]
    username: ENC[AES256_GCM,data:QcXFvTlKtSDXO43+lPsBrz4Tq53Rk0u6Q70uOiosc+w=,iv:xZdgOpXl3e1JOzaZtSLiKvQFStE8HMxbqHYK7pbYKGc=,tag:GMgHI7WsTbq6TApizLbyfw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZlEvc0daRWFIa2JNYVVJ
            ZDNJVUU0RTBVc05iZk40NmZ0LzhuMjFRQTJ3CkhkWXZiVzZ1WHczYXhnY21NRjNx
            QytTUWMydXJnSUlKa09FNFdtQ2gxbUEKLS0tIFBnUXpoN1ZvTXVqeDZNa3V5aWc3
            S3YzOVJmVmx2OVdiamdJc0hwRG1heE0K1aDMkvClQh8s8ElVxOTup65mwwgbAmfe
            MCDhM3vhzwFQPAwr9OQfk7nUb+v9dDPEwXfwcy1sNDMb5KkUOGW3fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T06:59:07Z"
    mac: ENC[AES256_GCM,data:cVmY4OpWMffP1YT1sM1eoANzSdFkfwsaBxeuC/2aaYcbnx+C+XhTV7kJHDVLrDCp+GHeE59GgGTwFusj2y+XhgH76vGvl4kkNgdf5I1na1kz2vSSzt4WJIqUqRWybUs0SkvgAlUjR2vZAO86DUec8MJPlkiq04f3dq2TktqFBM0=,iv:SFADK5TrgvXoJvzVyzeD6zrv5OKLbu1Jq8im8j7CGno=,tag:UoK35QTOWxMILfvxS7gz3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
