apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5PdDP/y7jU/z312INB7EfQm2LVts5mW9qoDO0RWaRDB3DPIc,iv:BkbE1Tn6DoguueQsWAoq5Bjk5mUvkgmrXLsP9Cbfyxs=,tag:8E/2J+sH/QWQJX9A3jAqTQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Rr4b6Ty5V1N5ud1xK/n4L2+6jf/rWqzifqkDg7+uDxteiDKnTaojUG7ji5lp/aayo0ZpK31AuG46P73uDPsZagMdTRqjndFRZex/uBfCJg3SSnjQV5Ac22vOtvuR0TqcW967dl83zdGKbXFCtEV/dSL7M/nr8tjic7IXxVrR/w9Hnl4ZVTkZTPQvH4QjnXOZyNdBGrNNloLO87VwTJTHRZQoruniJDt2+b81C7UaJg==,iv:Sidz0/Zev8Puwm9yP9CTN91MOZotyJauWEQNceTsYNw=,tag:UhGTd8hbyqjePalGxa7etw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS01ZUlNvNUorMU5QWTYx
            a09ENTR5ZWs3QUFLMXUvWWRZK3ZSL1VYSVdvCm1tTFRYakxCbUhBcFBmU1BGbFRu
            MXdTZUdVcndUNXVXWU94c3NtMlZMMGcKLS0tIEkyV3k0SXdqQlNrREpzeXlqWXBo
            ZkMvSmlpUzRLQU5JdEJmYWU4T0hnK00KZpsPt2LLVW2/xsoBTokNXYKn3nrWWuI3
            2LwOz1YRLWPDzHTpe1lfSbbs0CKBY8hLnBEcqJ4YCUGqc5N1PKMjsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T05:23:47Z"
    mac: ENC[AES256_GCM,data:QXcm006IzRZ0sogco2zdmi3tIeEjFaLXg/sskykQURyn0/aKE+qyxUWT1RT0xD0IXPj6QwjEsnudAXSIwLLwq1SS74vfcU6I5hsysXsG/rbjc/BdLuNFWlt6wP1h0phIcO6Igo5kvV7tej0OCzlki+y1qxvA8u2LFXcbKks95/k=,iv:5nhvu2Sxsfi9O2CT2PLdCnzSUvxd2WwqOzjLmv7aJyU=,tag:zzj7KJNllfyIktyiFjovag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
