apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZyEVHFONHrWpwmop6MZrE5tAqnlsaS75vfT0SFBWkC51U1dr,iv:VBaAvX2OnNeqvwZQupkyBLsIYJZhjSeEZQzFmNmUU2U=,tag:e2oTd7xMruDmBNrGG/klVQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Ple0aRqdEUzF5/DnBEMHf3eB1IF5PgLaH4KIlb5fLAZ7f0y5Ks71qr1leJ0CzoWrtBThBib/Vusm3v9CizpZul4px5wtldfJe9tIaeFSstqMtya5FZkqc0sQoD8+ijINPZ/OW3lq4r6l2zJlSfBN2yX1cQciIf4AufXOlyUdY6pPalizSQo5alBDxWdLMEwl6NRuRs84pt6sFjHYfuLpNZ571k7XFoIp9o4DqVS58Q==,iv:qrWOgg0V9ddvDXz4PW4t7I5tNRs59fpNVmQ+TBreDQo=,tag:KmcAKAvvodacGIu0OQodtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK2Vld3RxZVN1OHM4Q1or
            dnJTT3Q5dEtHNWtjdkFOYmxuem5TejJjbkdjCjMvWlJoSjM2U2s5VlIrRmN5NGFz
            Q2xHeVgxQ0RXaVIwMkcwV3JJUDNyVlUKLS0tIFc4b2Z6dUd5ZXRhUGtLRDh4UTVH
            SmxjVWlYYldoVEJ4K3JCZjVUay9NdHMKd0EThlr5kVlYTPOg34x4f8RMx42m6+w6
            NhADxdTc6KrRIFfG+YsUDIc3P7D2yooaLS2d0BxhOi33S6jg5tBdjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T02:58:09Z"
    mac: ENC[AES256_GCM,data:UlW3yccmb7AA+SyqwTLvERKOyZJi/AQEXUzIVwnVpsfjkWhBtabt4jYMfcw2J1+5Z7567u2WscUxBBMpBw4ySvSKNh95ZcZvnxVwEAasA+HhlzCoETBczupFpUhuvZBaCtgd+5EhayDsYezQb6//XwzXh5jQ3kisFe84/uwQijI=,iv:iRJIZOmYBHjzMPij/cluFFXVWNyWgPZEY7Y4OCSej+Y=,tag:CSdSx4BeJaHNBKh7h5hYvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
