apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LXl7lJ+dJrneXsnkLsZHorqd5+s4NGOd6k2YB+6kVDEZrckC,iv:DC2t/Vwj9GAKNUCohK9beFJCkqD+/61R8MeEK9QHn6I=,tag:YuJqTm8F5sXCLAnm3wQK+A==,type:str]
    credentials.json: ENC[AES256_GCM,data:b7Jnt/hJ3WngO8iq8TeLqqvkDhU9TiJrukLPn01+qEQhtuAi7z1qkX8ipuPkLdCSlL5HVNFXKsjOTtVOYaQTLb2sGKQNS5lLmElMRYkMvtVXoWVjgx8V1uEdAW79CakzCRJF8s1mWZ21idAc3KTLBI7GnKtTIRcMFcOxXwHWLdDbuWQFtpgjsiOXSF++gUK2kocEyQZoTZ+H0klTlTw2qXS/6dZH9TRTbZhlUEs14A==,iv:AGTu4pj7asUMrLbWof/M0/cBEMJwciItX0b8BjrvXCU=,tag:zsR2AQiJgBTGwMcI5czujw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eU9EWFVicjArMGMwL1Ns
            Vi82WFFjSXVMMXRHTmdIQUVVeTBCUzArUTNZCjFlbk53NEVqSkQrRmhRY1BpMHFD
            QTRwaGJaNDRlSU9UV3ZWMVo3bFN3VEUKLS0tIEVIV3d6S2dRQ0V0ckc2dzRmS01J
            bS9FSDRXUnllWVc1dmlQeHFKUUFndDAKaplVPNURyNA1LF4rZ/+jBPU5UcBtyhIp
            lT3mLt4fqeD2EvzQZ45tLbofhoguHGZV9/3UCs7F3sD0mPTHI22HCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T12:25:17Z"
    mac: ENC[AES256_GCM,data:H3Xv6RwOpqNI5F8gln6KGNud9NeVTSJnMuDCDMKjLsRDdoDpf1q+983HEcqKvp2GFfz8/ImEZbWB7su0qdPna1JW02nVuwRF/Yqv9hnxWA8YulaO9BFdZJ5lwEzxjz6vW21NwsRPQTkk55Qt67g+cZ3v2In6GfKg6PCzcu46eNs=,iv:WyN5iGTBkpICmnspVE/2GgwxewEzMxhK8x912U8A0CY=,tag:fLvkzWqRiYHeLsZ2aL3h9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
