apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vSE+YtijwqVbh+csfzj4DWovBxIsGKJViL7YAQICLQUvvIKC,iv:kPSp+m4qMybiYxZXW7zAvI2RgDgIYR1Tn3Mm71JzJi8=,tag:bui/WAC3mNStvKh82p6ftA==,type:str]
    credentials.json: ENC[AES256_GCM,data:n5GHvDIcDCYdV4fahNJ7B4xLuCXSCB6WSj8yI1keIRmcMGh0LmwTN1Xvxw/nPuwnaQgPVCnWr4JBwmWoeXWkqu0kw6bzxjC0pimcPQiXi45fBSA4QoOQTdZVgdJvdUWNzeeqxjNXD/xi06+ZuMEZhx66W9GXUl+UeX0SgB9PGnlncYBbjSTCEmZoitTTz3ukOEI3x5viQcb0EaJm6BjXPekqKY0PW5vEGXpe9nprcg==,iv:yLEy6gdQwwYi57uWOTrxYKI5MWarinH1eyNV6lAHTp8=,tag:qf7WeFOTxAA1FrEUPP//Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcXpWL3lIVy8zT0NTS2Y0
            Y1ZySEV2eUdod3lRT3BJNnNjeTdoSFBIY0JRCm1mSUJFczlKYjQrUC92bExQa3Av
            ZVRCUmwrT0IyelRKOFEveGtUYnBvQzgKLS0tIDhTbi9LUmxTRkNvZnBCa3Z5L3Zt
            bXpMR1Bpb2xpWDZoZlIyRHFZRnVkQzAKgzbBzlWfbNZe2P7tQrItbf/2Bt/dxXYx
            4tE8EdVjTYvOsivMKAv8ro7EgWXhJB2JX31KULQhSIwhD4yli2UAsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T11:02:37Z"
    mac: ENC[AES256_GCM,data:sJ2kRQwoL9N4/CyTtnaOiP9FrWIQ07raZN/ZWoqDIjJPlz1g0awMmJ/e0CCYJ8vwoh1pH47kBE1ScOFAdZ/3ryEfQ5IfiHYo1Ukb6oCsaBsyxY8lhzx8z6YVDLbA4nFQKrG4DAb4Qem/KCaPmoXiVhGNapOIVx5EsMVhLnZTJt0=,iv:i8APEIrGZ6NXPI/HlRaJ1UXUdi5V0yKsPBd9oXL+5IM=,tag:9LS6Wpt8Jfsv/LSyTKT//A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
