apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZKkiPTWGPI7XbF/GcVUR8FMCMDMD24wNSCqmXfU4aLtMQjqx,iv:TUGD7qXZ28wJI+tSKaP8h+XNBlvfeQurL0Sf9R2hCq4=,tag:3s2i+fPdvWuRnW0F351XBg==,type:str]
    credentials.json: ENC[AES256_GCM,data:QQ1LzB+FIe1IuYKA+FNY3IHUy44tBxHBj6CvJjuvQFD2Vfn0yBXjvqcH3ijR/FW0LI7udhy8Jm4mcCBGCBv1uPlqVVsXWJBz+qvjsSg/CrQrsx6YOUiX1d2OYlugJ0cAE8PW2GNlFTugXSReERHDpsbl3cc5aWZj91zaMxdrISNZ2CIWZsYDtRr9A/qMg4fmlGdVBrrEYYTVySjb/h6ptuKArclgJUpFTCfEbk/Rcg==,iv:m6Hr90caxtC9e5b88EMMI0617OWRjvX/lJebcIQXveU=,tag:gWkUQ6jWgetihE03orzJZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMGJXTktFZGpwL0pQc2Q4
            TWY4UkVud2pOcDI3YXlNZ2hsM2tpbEFFdkZZCmMxK3lESEFTUm1POG1ETFpMRDdi
            NFZFS3pyQWMrL2VrUDUyYmhDQmpTU3MKLS0tIEhPblVVejZPWkxQZitBaklpNHhM
            R3FjVkphajlvUS9NWmJySm9RSlo2c1kKsWZIBZRIDOPIdD7sRK54aCMDHe/l/41s
            IPrMrZr9bYEg2PJ/QDf/tib9qBqJAWMspvWOlL0kVNfF7uR/Iq8XrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:05:52Z"
    mac: ENC[AES256_GCM,data:GlW+R404O+SkOxJgYnxGEh3Xhx8cDFKrLVWNrJ4Sn0Id91tR+mCh1akGAsFs0FAJLR/E1b4l4PP57lRppSN8SOLxvsMi4YF0T+2tilOQH1okNIRegId1r+lnYnoeFVqkSVji4X19wglqI4G/NJ+4t1fw2ohc9O7ecWmTNGpHCcQ=,iv:jrIzpSTn2Fs3cdWujV/zRyytihYMvdgsGK7XzVQ6Qtk=,tag:aLRDshPy+v/EXL4VYFyrqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
