apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:TcJ9EF6N2Ew2sEOUIzBqEHvUCfaBpkxKBraxCdVFdb4Al1C5,iv:AU8FUp1iYUx3rGCrhffKqbMZ4qYlytQn+v9sDtfK8n8=,tag:LKfKB+bMvAvl/ve+l5zeEQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:O+KXhoUiIqzJmxwOX+Zc5wolpIN5kbgiJQjbS/kDul5bktGDjxr8C5taKpa8U8CiKeKh2nUEIa0eB73tPdbhZ2a69ssGfFPspgxk7XgDcLfTCeTNZtAAZ0NUYm8pf8OaYe8s3cF/M8c1XTKQSSB1qJSK4/La1/PM7JumE0iEAkWFmC/NskGJ4TyKu/gPmpUKjZUSNFiBYz2hNxyHUs6jOlkIBq1PaS+kj5l0jMkcoA==,iv:bGm4sybdjwGXudV4z0Idx/+Lz084QYqKbFS5PxItSUI=,tag:2vjg72gEXfw37YX5qmF05g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bVk2TExDc2hjb1AyMlRj
            ZkZyNXBReDFKMnVIZHVwVDd1Y0ZuVFBBcURZClFpYjZNMnNZWVlCbTlZaGwvaVhi
            UDJkU0tLRU1taVVKd1Yrb2RtZ3Jpd0kKLS0tIE5sVkozZldyR3V2RnpoNE5BUC9W
            VHhHazRiaFkzQmlUYi9NOW5kTVBBbTAKTBlcf4EsSTTn3blWCDVPaGA7oTU74Sgg
            +2pwzoCth/CwbnpQSboYOvN7B9qjRaOLmH3S3jiAhK29g0jw/Tx6Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T06:59:21Z"
    mac: ENC[AES256_GCM,data:zup640EBRmTUV+5lxnF6TF8HhtST2Tz6VxNSJ/1Y1woPAg+M7z/PgxX9cwEg5w4oTiqDBuerFw4S3HowA7eEqQFfnxXLuFaBSgeu6GFnr+XorOZfE00LAUVgCjSAT2ZiO6AZpUQ32vTAWFGAZK1L54CuxaCaHeJ91RZfrIATE0g=,iv:dYdNwguE8uh8bcxFe0s10yXb8U6gok+DwURf9TwT8ec=,tag:DXXY3xaXGy6OPIMgLTULmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
