apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/2L6Cv7Jm7sf254jR3CkjHxEEIa+3cDrNwKdYgogM6DNzdxz,iv:xlhxYegT9SPXZvMMv96uS/JeI+fb79FY1bRRi36eaJ0=,tag:4UJNlKI53JN7PtK1kKVo8g==,type:str]
    credentials.json: ENC[AES256_GCM,data:hS2Ysvk/EKYoAQucM+jT8Bz9iVYEOkgGX+cfml2k3CfgGm1W/DpZ6x4Rk1rTMFmsQp3dEx7qVVJWdnXHYaa2Rf1nGEh9UBISQvzdtDBxpFFW2n+aQ0UafqFP+kRtS6O0rwRdZsmfhQsrPZUgnQ7GqjCJXDwdKOp8hWC5SFQu0dbRr1er1BKL3tN6Tg4rUR7AUi6W8gAhz5EtRsv6JEvyjbjXE11eq1Wpxc39dXmTYg==,iv:gpdX5nO3C8Oz5cU6rvSyeSu7yuGe+tbdiQ/2qLurplc=,tag:Woj430udFEveGs4f/8IY0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YWtDcFlsdnpDVUZVVGdC
            L2Y5TENpU3p0cE4zTytab1pPaUNMcEFnemxFCmlKc2V1OWlkbEhSWlZTL3ZpOWsv
            bzVCejhsUVo3WCtUckxUMDBVK3I1UjAKLS0tIE5YVXB1SGxsVU9hZTE2b2lqV2RI
            ZVZSWGxjVSsrVEllUXJ0d1VNMkZtdnMKUK6Enw1Hkyan5xrktuEXC3xPpL9MYsnr
            DK389ZBjjAo9+wj6j1ItG3ZC+5/D+0Z1ubMAx4XTHaUHv3uGMKJwGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T13:02:32Z"
    mac: ENC[AES256_GCM,data:Bth/2NAzCypvsIk2Hg418vDzaHxYfoouPRXe9RIiv9vOi5fzTtSiAXA4IriUj9Z2SNhrJKimuVKgD/3kyGCteT9bnS4tP+We4yuFCSS6szCM59nifO+kgToV67F4U4ZRGcGUwqcRAt0Ju8djvlcET3X7TubzMi6K/FG6lsJqoH0=,iv:eEI4WljF3lYuIWVIlLVZzknYj11e4sXDS9AnjYFkYvk=,tag:pvOvZJ95TiVIw8XhJvNIcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
