apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WtDGtNxPPKNM7RRnfWcw0ldQCCYs2jtZta61KxWBT4mErBjM,iv:gzJMGFSG8PpPQKqW11ZniR9TZWCTnxqAmiRBa9UUWVw=,tag:P/rHf2vAMHAz2X6UH2ZwMw==,type:str]
    credentials.json: ENC[AES256_GCM,data:QejZWuEfwGGeKyzTnn+Ui767PtbzG91hEPDUNbA0jHTAIp9g6jSNMz5BuLNgkA9Ro76OGdGbACNGuEkb52BXflIjA+deDes9nMRoYGOi51lMcb24J8W9Ndp2zfHTIGPwh9Etr+x1IfnZntIKiVR5Ho/3WYC61y8ZoP6ek5jzU+uNR2BsNBA7B2NHyOblbDeX5RWuSaK3D3/FUtdGNj8SFU9noBePyfhsIPUMUlj/mQ==,iv:/pgLAsZyrMSwjitGBAACRO7SslAb3U85nE22vbqum48=,tag:tul+cIzf1CwY2MH1gGpidA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVjY2VEV1WmtDcFhNVCto
            Qkpra3J2TERuYTNZYjkyZ3VoOC9YTVczVkVVClFRR1FuYTBMcEdCcWhPQklJbVlN
            dEc5cEZJUTI1S3N5aXZNQXZpRGhSUEkKLS0tIGxLTGI0ckxGZlJLajR4eW1MN2g0
            VVBQWHpNbEhFVGtPcXpBRVRZNnIraTAKmmcsQAoQxMcgAFfNQbgUSXrvNOX1UvoH
            cE7e1CsQLGLLDBAoJe86JLP/ftPcdoJtZ9ChgqTamxjFTX8nPgktzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:07:11Z"
    mac: ENC[AES256_GCM,data:ilkUXYifmAhxsLncTXEJRULqNyEQu6st+XjHbGEj80+3mtvntFUrAWoKDzUJdLu7eBEjXYk4gm2VZhhxSdY1Lr7jYoItUgMshaS7XV466MbFeUN/pHOS/LPIBt4LIigZ9Ylg9+Zl2E/IibNxJZ5OHmARBvcGwhrfhOL1kWa3jbI=,iv:ojLmpUrA9tsxgHBQ1XlIHyzWjjbWWD4UMSrSTmyuGW0=,tag:TuMP33U5VHLkkTOwvD/uQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
