apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GZxmUuXMyeVgkzAsz7Shdy8K0bjaLc1N6faBzhNBff+1tmt6,iv:x3SFgHLm2vY5uXw9dv3uanubuG/R0jvYvrHVxW+GlA4=,tag:Ua8SHfYbvtTw+7zIufLerA==,type:str]
    credentials.json: ENC[AES256_GCM,data:bABQ8WU8tseGM3q3rlGYdDcaidoRMriRTIaK/8t39BCufeLcAWyiHR/xStjEpp8moim5CsTxsYcWqD+Wa0FOnU2QSGKJJCR0OiQH5/RfZHZPbm+QjCqzHZVQiao4WTsK53vf13x6GKw5IKDjYycKZ/zfzwcwYtq03cdT+Mj08BuX5FYkLPtL7pquYFw7adHkYAf9iaK671LTh6M+y4e4qEcHcd5uAKA4w536XgifYA==,iv:BFPukvFKi/Se24aL1QDL9Kl3xC23/pywnidmSCp55nQ=,tag:XQbtig48hs7roJkr+JTTYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQjFJblVsWDRXRHFQTzhY
            dElSQW9BeTNtY3o0Z1hXT3BzV2ZOUHEwYjJnCmc3RWFJeDVkeGt6RmNjelhQZGUr
            NDE2aVdYQ3ZxWk9iYXl2U29PU2JOSmMKLS0tIDBydTR6dnkvMmJ1YlFjS1hlY2k5
            RDA5Q2Y5QVNadWtxTERDbEgyQWJTK3cKU8ZhOTaQYmgZI5TaJ0b2MTinuV2O1cXn
            TJnp8UCaBJc8KdMRO8C1Ua+aArrCAAGu03+xBzMncXfPZzMXg3vc1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T16:37:28Z"
    mac: ENC[AES256_GCM,data:GHSG8toGhXWV6M2uA5XuSTYtxcmjfAAxPDgnwfXYqxUL0VDBa1A0XCuySxePKiRMpKOvkEdeW8WDRKtuLCXUfmHzrak2SXq6EmbIfqQ4E0qcfleR8jo/xrsgNrGDyNMzSVu/lgBWNlWLa5NHdsKDVCyrHHncCM9Usyp7b46zbX8=,iv:aYhxgF3e7a8SNYfFAVVOeqYNyZX0lPqX4Bbu1zej5KI=,tag:Gp32tCCJXIt29d/ftEZwVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
