apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:xi+ydTcLOk3GDm/dZcaX0J431hLLJAQmYmMnGmhlryOHnVS2,iv:PYxuQCdSSTh7m0QZsPeJiz8VsIKIfayV05Rc4XswqLU=,tag:VcFgdZTbAxosKEo/THA06w==,type:str]
    credentials.json: ENC[AES256_GCM,data:+sGMp5Ts6+mO2ndvv1DQKsrsgn9TBoPYdnl8PxQXZIUG851d1SKdGZfkWbRSZrurZimHiJIZ8Sr4QORwm9XwGn8exVn6GZiKbVXyyCs9P73juEBcVzfZPimwe+PCtsjwy6yML/QkFtQANKsGoswyGzgeMNIx6Mxbu5u/SdGfhzQQ0P0xNGeLxWQExN4KhbhwF9w2DLGJcxLSu8vX02OxNtSHEjnhdqkxytDUxzPoFg==,iv:MNID9Krl+nTfXVXN1omniP2XNw1j+OaSTYU+P19sxTo=,tag:YA4VvgUoKLZhcrvExUb9Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2MrWnI3U3lBRmRFWWNO
            VWszSm5ReXdTU3k5M3R2SHVwZXNXRXdYUVhjCjNISUdDeTJIbFZDbnJzVEhLMFdj
            MEZLN1hxUFNDTnRkVFhqSW1GYjNVb00KLS0tIG5lY3I1dG96L25rTVhmRzA3Z1pl
            ZVlqUm00SjU0UktrUmFWVDF5MW95aW8K4G7/zEJBf8hBL//fvu3JXt55Ae6NK5g+
            8T/nZ0O0XYiR833sBueQMI1phISXnYaX3F6rSFAxX8r9jHs74AOBVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:10:53Z"
    mac: ENC[AES256_GCM,data:tWoYth2jj/g6qCJjpv2lFJz8D6SLUvSej3vtGMoFaTiYNJXdQzkAT+JELbYefo7HHVsIBhwsOO8cyNNCXS5ypIewtv+xiRNP5JK5lXMEc9roq81O9aopu0tN0rspUhc3fbkAQvSHymV6vmWBwR7DGge3IK/nCaZN+USFf7UDxSE=,iv:6E7x6ksUC2UPCovs/dpsJzgFLtyCNbLqmY2KFwPlwZ0=,tag:f/0vVUPvgukcevaUagVPxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
