apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WbnPc8uAc7KThj44n2w1q+dfIOTOt6pxyjzhC2aobmiCNtsM,iv:Y3NVa058xVF//lUj+5wjjJ/OlGOs36VS5UqTNJwlwCw=,tag:du0pG4In08/3+riQuFJ+Bg==,type:str]
    credentials.json: ENC[AES256_GCM,data:iADauxm2d0IS8gC3kte27dmGOiDD4ANB9qae4TNCl4fe1BHHr4BXKVndUZ+iB5Q9GoeJZkqn3xf7UftjLJlB7ynU89RmOSY84Cl/CS7wA798pEk6KJOZDwWpiKkPIVz/0KDYMFvWpUonKbGwPXW0avsCO7FwRwiKeWeOU3onCH6bC3xBKBA6xweSBob/8+64+zJsu1ZLtLTV+UYMOG67+/A4uO9rdL1yOQ8I4znQ5w==,iv:ASoZPrnIrTd//xfF/QJs38ByPcTPfNGRF6t0ayBINQY=,tag:Ql+zlMmRarpSE0ZewKn/jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ3cwZlpoWDE2RXRIMm0r
            aUMrZ1d6Y01iOUNHUWRTU2s0Tk4xY0R1cEhJCkIzZnM4eFlYcWhxUTNic2lJQVJH
            SXNSeHhGY0gybTZ6Z1ZRZERDMmlOVmsKLS0tIFhUUkh6bWdLaVBiZTk4SS9td3JV
            SDNlVDI0Z2RseldNRHo1Y1FsMk95ZjQKe1GmvJ3AR8XwXGIwWSuu8SEECw5DwbsI
            4N6GF65QLdzvDNX4+97eeYxSMbtdxYUW+M9oXY+DMpdXNQ8y1t/cFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:26:25Z"
    mac: ENC[AES256_GCM,data:r4Cvi2yYKfABJJj0EnCO5wFO+JMwBXoCudk/w7OB/3SO5sq53RXJ6jvLbNt4oUvDHyFauygIxZsB7rumQQff+/C9YOPKPymtfTNuFF9khT/9YgZsat0MJezcWGHtR+LJcLEQMBR7Y8rNOjConmjKSJBUInYslvHFNMgamZMQAuc=,iv:6EfPbw5cvuK9k5E5X+VNGgOZf5y0pHqT0FstyKBqw44=,tag:lG4YSv/jyJFFhhSyUUd4hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
