apiVersion: v1
kind: Secret
metadata:
    name: ghost-secrets
    namespace: media
stringData:
    MEDIA1_GHOST_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:Er5VctpVWsEdqsauifcKkWHtZnpZlDCHg5Pa0uFs7Mw=,iv:VpbTwcLITSLkM0pdzyugqCuzz0qa0J8cELg4BLSbrAU=,tag:cYe/MLX9YSRiHILAyZKTDg==,type:str]
    MEDIA1_GHOST_DB_USER: ENC[AES256_GCM,data:J3sqcPzL,iv:37zcWS8Y66DGKlVwV578gZM/Kp9GgMZqq3MiSYyM4b0=,tag:kqRxDNKoCDr4UzPg3tiGYA==,type:str]
    MEDIA1_GHOST_DB_PASSWORD: ENC[AES256_GCM,data:hZv6sfoQlzjRgFxXstCnYaU1cQAW/5D2T+GVnq2Ay1E=,iv:GpfxAwZl26nYhua4tN4l0zlrHfcTM9durqppOUPNl+Y=,tag:heQLCaoUAS28EB6WgZRBig==,type:str]
    MEDIA1_GHOST_DB_DB: ENC[AES256_GCM,data:JL4RQQjIK+A=,iv:FkWlQbU+VbLLTh2Q8sGBwbHOzt14YxO0yHiDPVOYKAY=,tag:0wncYBM49rt3OEPBw8zjeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dXFGUmppM1BtWGd2TjNR
            TkZqa1E5S1VoZnRKN0x3SnFlL1ZidHBpMTJZCmFwZmhhOE5nalBqdU1BNXNOUG40
            eDFRR0laWm9EUzVuc3ZJeUN4b1ZOWXMKLS0tIHc0UXpVL0RHcUxFSHhBdldRY1NQ
            QmRnZ1hMUE1GRVdCSGovVHdkUzkxdjAKEXsRywOO4D6jJCit/FTRgLP0Tp+sYLJr
            SNN2D4Ox6ZZviVu1HBYw/FqAN2DdfsgrUKFMT5d8i3Ag8t1hkGkblg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T11:09:24Z"
    mac: ENC[AES256_GCM,data:iA1pzqRmfm+nUul8UA+5YT9PT+Xa3aAkzTE5sA0WybqftC4zmEZJp7jnIpXJhFkbgXeORlYLLC1yJjs+taFMa4WNRb77ar6HgOsNhjI6SM/Z6VJ8g0HOV0kufsxInAcKLPxJq3fSdbImZG0mQ2Z8ZlqyUEyygQxYsQ6w1Ucc/TU=,iv:VB6QJvn/8sbWvc9LAei5CzBYTjsVo7Q3+PoVXrKY7rI=,tag:df2UnDmYwzsX4uRbzqFC0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
